/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import itson.reservatrenesmongodb.dtos.BoletoDTO;
import itson.reservatrenesmongodb.dtos.CompraBoletoDTO;
import itson.reservatrenesmongodb.dtos.ViajeDTO;
import itson.reservatrenesmongodb.dtos.ViajeDisponibleDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.BoletoServicio;
import itson.reservatrenesmongodb.servicios.implementaciones.PasajeroServicio;
import itson.reservatrenesmongodb.servicios.implementaciones.ViajeServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IBoletoServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IPasajeroServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IViajeServicio;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author cmartinez
 */
public class dlgComprarBoleto extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgComprarBoleto.class.getName());

    /**
     * Viaje seleccionado desde la consulta de viajes.
     */
    private ViajeDisponibleDTO viajeSeleccionado;

    /**
     * Tipo de boleto seleccionado inicialmente desde la búsqueda.
     */
    private String tipoBoletoInicial;

    /**
     * Creates new form dlgComprarBoleto
     */
    public dlgComprarBoleto(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null, null);
    }

    /**
     * Crea el diálogo de compra para un viaje seleccionado.
     *
     * @param parent Ventana padre.
     * @param modal Indica si el diálogo es modal.
     * @param viajeSeleccionado Viaje seleccionado en la consulta.
     * @param tipoBoletoInicial Tipo de boleto elegido inicialmente.
     */
    public dlgComprarBoleto(java.awt.Frame parent, boolean modal,
            ViajeDisponibleDTO viajeSeleccionado,
            String tipoBoletoInicial) {
        super(parent, modal);
        initComponents();

        this.viajeSeleccionado = viajeSeleccionado;
        this.tipoBoletoInicial = tipoBoletoInicial;

        setTitle("Comprar boleto");
        setLocationRelativeTo(parent);

        configurarComponentesIniciales();
        cargarTiposBoleto();
        cargarSexosPasajero();
        cargarCiudadesRegistradas();
        cargarEstadosRegistrados();
        cargarDatosViaje();
        actualizarPrecioYDisponibilidad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloComprarBoleto = new javax.swing.JPanel();
        lblTituloComprarBoleto = new javax.swing.JLabel();
        lblSubtituloComprarBoletos = new javax.swing.JLabel();
        pnlCuerpo = new javax.swing.JPanel();
        pnlDatosViaje = new javax.swing.JPanel();
        lblDatosViaje = new javax.swing.JLabel();
        lblTrenViaje = new javax.swing.JLabel();
        txtTrenViaje = new javax.swing.JTextField();
        lblOrigenViaje = new javax.swing.JLabel();
        txtOrigenViaje = new javax.swing.JTextField();
        lblDestinoViaje = new javax.swing.JLabel();
        txtDestinoViaje = new javax.swing.JTextField();
        lblFechaSalidaViaje = new javax.swing.JLabel();
        dchFechaSalidaViaje = new com.toedter.calendar.JDateChooser();
        lblHoraSalidaViaje = new javax.swing.JLabel();
        spnHoraSalidaViaje = new javax.swing.JSpinner();
        lblTipoBoleto = new javax.swing.JLabel();
        lblPrecioViaje = new javax.swing.JLabel();
        lblDisponibilidadViaje = new javax.swing.JLabel();
        txtDisponibilidadViaje = new javax.swing.JTextField();
        cmbTipoBoleto = new javax.swing.JComboBox<>();
        lblMontoPrecioBoleto = new javax.swing.JLabel();
        pnlDatosPasajero = new javax.swing.JPanel();
        lblDatosPasajero = new javax.swing.JLabel();
        lblNombreCompletoPasajero = new javax.swing.JLabel();
        txtNombreCompletoPasajero = new javax.swing.JTextField();
        lblSexoPasajero = new javax.swing.JLabel();
        cmbSexoPasajero = new javax.swing.JComboBox<>();
        lblFechaNacPasajero = new javax.swing.JLabel();
        dchNacimientoPasajero = new com.toedter.calendar.JDateChooser();
        lblTelefonoPasajero = new javax.swing.JLabel();
        txtTelefonoPasajero = new javax.swing.JTextField();
        lblCorreoPasajero = new javax.swing.JLabel();
        txtCorreoPasajero = new javax.swing.JTextField();
        lblDireccionCallePasajero = new javax.swing.JLabel();
        txtDireccionCalleNumeroPasajero = new javax.swing.JTextField();
        lblDireccionColoniaPasajero = new javax.swing.JLabel();
        txtDireccionColoniaPasajero = new javax.swing.JTextField();
        lblDireccionCiudadPasajero = new javax.swing.JLabel();
        lblDireccionEstadoPasajero = new javax.swing.JLabel();
        btnConfirmarCompraBoleto = new javax.swing.JButton();
        btnLimpiarPasajero = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbDireccionCiudadPasajero = new javax.swing.JComboBox<>();
        cmbDireccionEstadoPasajero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloComprarBoleto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloComprarBoleto.setText("Comprar boleto");

        lblSubtituloComprarBoletos.setText("Complete los datos del pasajero");

        javax.swing.GroupLayout pnlTituloComprarBoletoLayout = new javax.swing.GroupLayout(pnlTituloComprarBoleto);
        pnlTituloComprarBoleto.setLayout(pnlTituloComprarBoletoLayout);
        pnlTituloComprarBoletoLayout.setHorizontalGroup(
            pnlTituloComprarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloComprarBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloComprarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloComprarBoleto)
                    .addComponent(lblSubtituloComprarBoletos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloComprarBoletoLayout.setVerticalGroup(
            pnlTituloComprarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloComprarBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloComprarBoleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloComprarBoletos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCuerpo.setLayout(new java.awt.GridLayout(1, 0));

        lblDatosViaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDatosViaje.setText("Datos del viaje");

        lblTrenViaje.setText("Tren");

        txtTrenViaje.setEditable(false);
        txtTrenViaje.addActionListener(this::txtTrenViajeActionPerformed);

        lblOrigenViaje.setText("Origen");

        txtOrigenViaje.setEditable(false);
        txtOrigenViaje.addActionListener(this::txtOrigenViajeActionPerformed);

        lblDestinoViaje.setText("Destino");

        txtDestinoViaje.setEditable(false);
        txtDestinoViaje.addActionListener(this::txtDestinoViajeActionPerformed);

        lblFechaSalidaViaje.setText("Fecha de salida");

        lblHoraSalidaViaje.setText("Hora de salida");

        lblTipoBoleto.setText("Tipo de boleto");

        lblPrecioViaje.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecioViaje.setText("Precio: ");

        lblDisponibilidadViaje.setText("Disponibilidad");

        txtDisponibilidadViaje.setEditable(false);
        txtDisponibilidadViaje.addActionListener(this::txtDisponibilidadViajeActionPerformed);

        cmbTipoBoleto.addActionListener(this::cmbTipoBoletoActionPerformed);

        lblMontoPrecioBoleto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMontoPrecioBoleto.setText("$0.00");

        javax.swing.GroupLayout pnlDatosViajeLayout = new javax.swing.GroupLayout(pnlDatosViaje);
        pnlDatosViaje.setLayout(pnlDatosViajeLayout);
        pnlDatosViajeLayout.setHorizontalGroup(
            pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosViajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDatosViaje)
                    .addComponent(lblTrenViaje)
                    .addGroup(pnlDatosViajeLayout.createSequentialGroup()
                        .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dchFechaSalidaViaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(lblOrigenViaje, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOrigenViaje, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblFechaSalidaViaje))
                        .addGap(23, 23, 23)
                        .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnHoraSalidaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraSalidaViaje)
                            .addComponent(lblDestinoViaje)
                            .addComponent(txtDestinoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTipoBoleto)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosViajeLayout.createSequentialGroup()
                        .addComponent(lblPrecioViaje)
                        .addGap(18, 18, 18)
                        .addComponent(lblMontoPrecioBoleto))
                    .addComponent(lblDisponibilidadViaje)
                    .addComponent(txtTrenViaje)
                    .addComponent(cmbTipoBoleto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDisponibilidadViaje))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlDatosViajeLayout.setVerticalGroup(
            pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosViajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spnHoraSalidaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatosViajeLayout.createSequentialGroup()
                        .addComponent(lblDatosViaje)
                        .addGap(18, 18, 18)
                        .addComponent(lblTrenViaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTrenViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrigenViaje)
                            .addComponent(lblDestinoViaje))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOrigenViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestinoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaSalidaViaje)
                            .addComponent(lblHoraSalidaViaje))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dchFechaSalidaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoBoleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(pnlDatosViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioViaje)
                    .addComponent(lblMontoPrecioBoleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDisponibilidadViaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDisponibilidadViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pnlCuerpo.add(pnlDatosViaje);

        lblDatosPasajero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDatosPasajero.setText("Datos del pasajero");

        lblNombreCompletoPasajero.setText("Nombre completo * ");

        txtNombreCompletoPasajero.addActionListener(this::txtNombreCompletoPasajeroActionPerformed);

        lblSexoPasajero.setText("Sexo * ");

        cmbSexoPasajero.addActionListener(this::cmbSexoPasajeroActionPerformed);

        lblFechaNacPasajero.setText("Fecha de nacimiento *");

        lblTelefonoPasajero.setText("Teléfono *");

        txtTelefonoPasajero.addActionListener(this::txtTelefonoPasajeroActionPerformed);

        lblCorreoPasajero.setText("Correo electrónico *");

        txtCorreoPasajero.addActionListener(this::txtCorreoPasajeroActionPerformed);

        lblDireccionCallePasajero.setText("Calle y número *");

        txtDireccionCalleNumeroPasajero.addActionListener(this::txtDireccionCalleNumeroPasajeroActionPerformed);

        lblDireccionColoniaPasajero.setText("Colonia *");

        txtDireccionColoniaPasajero.addActionListener(this::txtDireccionColoniaPasajeroActionPerformed);

        lblDireccionCiudadPasajero.setText("Ciudad *");

        lblDireccionEstadoPasajero.setText("Estado *");

        btnConfirmarCompraBoleto.setText("Confirmar compra");
        btnConfirmarCompraBoleto.addActionListener(this::btnConfirmarCompraBoletoActionPerformed);

        btnLimpiarPasajero.setText("Limpiar");
        btnLimpiarPasajero.addActionListener(this::btnLimpiarPasajeroActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        cmbDireccionCiudadPasajero.setEditable(true);

        cmbDireccionEstadoPasajero.setEditable(true);

        javax.swing.GroupLayout pnlDatosPasajeroLayout = new javax.swing.GroupLayout(pnlDatosPasajero);
        pnlDatosPasajero.setLayout(pnlDatosPasajeroLayout);
        pnlDatosPasajeroLayout.setHorizontalGroup(
            pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDireccionEstadoPasajero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreCompletoPasajero)
                    .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                        .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSexoPasajero)
                            .addComponent(lblDatosPasajero)
                            .addComponent(lblNombreCompletoPasajero)
                            .addComponent(lblTelefonoPasajero)
                            .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbSexoPasajero, javax.swing.GroupLayout.Alignment.LEADING, 0, 119, Short.MAX_VALUE)
                                .addComponent(txtTelefonoPasajero, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(12, 12, 12)
                        .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dchNacimientoPasajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                                .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCorreoPasajero)
                                    .addComponent(lblFechaNacPasajero))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCorreoPasajero)))
                    .addComponent(txtDireccionCalleNumeroPasajero)
                    .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                        .addComponent(btnConfirmarCompraBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiarPasajero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                        .addComponent(txtDireccionColoniaPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbDireccionCiudadPasajero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                        .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccionCallePasajero)
                            .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                                .addComponent(lblDireccionColoniaPasajero)
                                .addGap(109, 109, 109)
                                .addComponent(lblDireccionCiudadPasajero))
                            .addComponent(lblDireccionEstadoPasajero))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDatosPasajeroLayout.setVerticalGroup(
            pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dchNacimientoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDatosPasajeroLayout.createSequentialGroup()
                        .addComponent(lblDatosPasajero)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreCompletoPasajero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreCompletoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexoPasajero)
                            .addComponent(lblFechaNacPasajero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSexoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoPasajero)
                    .addComponent(lblCorreoPasajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDireccionCallePasajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccionCalleNumeroPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionColoniaPasajero)
                    .addComponent(lblDireccionCiudadPasajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionColoniaPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDireccionCiudadPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDireccionEstadoPasajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDireccionEstadoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosPasajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarCompraBoleto)
                    .addComponent(btnLimpiarPasajero)
                    .addComponent(btnCancelar))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlCuerpo.add(pnlDatosPasajero);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTituloComprarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloComprarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarCompraBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCompraBoletoActionPerformed
        try {
            CompraBoletoDTO compraDTO = construirCompraBoletoDTO();

            IBoletoServicio boletoServicio = new BoletoServicio();
            BoletoDTO boletoGenerado
                    = boletoServicio.generarBoleto(compraDTO);

            actualizarDisponibilidadViaje();
            actualizarPrecioYDisponibilidad();

            int respuesta = JOptionPane.showConfirmDialog(
                    this,
                    "Boleto generado correctamente.\n"
                    + "Folio: " + boletoGenerado.getFolio()
                    + "\n\n¿Desea comprar otro boleto para este mismo viaje?",
                    "Compra exitosa",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE
            );

            if (respuesta == JOptionPane.YES_OPTION) {
                cargarCiudadesRegistradas();
                cargarEstadosRegistrados();
                limpiarDatosPasajero();
                actualizarPrecioYDisponibilidad();
            } else {
                dispose();
            }

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_btnConfirmarCompraBoletoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPasajeroActionPerformed
        limpiarDatosPasajero();
    }//GEN-LAST:event_btnLimpiarPasajeroActionPerformed

    private void cmbSexoPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoPasajeroActionPerformed

    private void txtTelefonoPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoPasajeroActionPerformed

    private void txtCorreoPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoPasajeroActionPerformed

    private void txtDireccionCalleNumeroPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionCalleNumeroPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionCalleNumeroPasajeroActionPerformed

    private void txtDireccionColoniaPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionColoniaPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionColoniaPasajeroActionPerformed

    private void txtNombreCompletoPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompletoPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompletoPasajeroActionPerformed

    private void txtOrigenViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenViajeActionPerformed

    private void txtDestinoViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoViajeActionPerformed

    private void txtTrenViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTrenViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTrenViajeActionPerformed

    private void cmbTipoBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoBoletoActionPerformed
        actualizarPrecioYDisponibilidad();
    }//GEN-LAST:event_cmbTipoBoletoActionPerformed

    private void txtDisponibilidadViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisponibilidadViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisponibilidadViajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgComprarBoleto dialog = new dlgComprarBoleto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmarCompraBoleto;
    private javax.swing.JButton btnLimpiarPasajero;
    private javax.swing.JComboBox<String> cmbDireccionCiudadPasajero;
    private javax.swing.JComboBox<String> cmbDireccionEstadoPasajero;
    private javax.swing.JComboBox<String> cmbSexoPasajero;
    private javax.swing.JComboBox<String> cmbTipoBoleto;
    private com.toedter.calendar.JDateChooser dchFechaSalidaViaje;
    private com.toedter.calendar.JDateChooser dchNacimientoPasajero;
    private javax.swing.JLabel lblCorreoPasajero;
    private javax.swing.JLabel lblDatosPasajero;
    private javax.swing.JLabel lblDatosViaje;
    private javax.swing.JLabel lblDestinoViaje;
    private javax.swing.JLabel lblDireccionCallePasajero;
    private javax.swing.JLabel lblDireccionCiudadPasajero;
    private javax.swing.JLabel lblDireccionColoniaPasajero;
    private javax.swing.JLabel lblDireccionEstadoPasajero;
    private javax.swing.JLabel lblDisponibilidadViaje;
    private javax.swing.JLabel lblFechaNacPasajero;
    private javax.swing.JLabel lblFechaSalidaViaje;
    private javax.swing.JLabel lblHoraSalidaViaje;
    private javax.swing.JLabel lblMontoPrecioBoleto;
    private javax.swing.JLabel lblNombreCompletoPasajero;
    private javax.swing.JLabel lblOrigenViaje;
    private javax.swing.JLabel lblPrecioViaje;
    private javax.swing.JLabel lblSexoPasajero;
    private javax.swing.JLabel lblSubtituloComprarBoletos;
    private javax.swing.JLabel lblTelefonoPasajero;
    private javax.swing.JLabel lblTipoBoleto;
    private javax.swing.JLabel lblTituloComprarBoleto;
    private javax.swing.JLabel lblTrenViaje;
    private javax.swing.JPanel pnlCuerpo;
    private javax.swing.JPanel pnlDatosPasajero;
    private javax.swing.JPanel pnlDatosViaje;
    private javax.swing.JPanel pnlTituloComprarBoleto;
    private javax.swing.JSpinner spnHoraSalidaViaje;
    private javax.swing.JTextField txtCorreoPasajero;
    private javax.swing.JTextField txtDestinoViaje;
    private javax.swing.JTextField txtDireccionCalleNumeroPasajero;
    private javax.swing.JTextField txtDireccionColoniaPasajero;
    private javax.swing.JTextField txtDisponibilidadViaje;
    private javax.swing.JTextField txtNombreCompletoPasajero;
    private javax.swing.JTextField txtOrigenViaje;
    private javax.swing.JTextField txtTelefonoPasajero;
    private javax.swing.JTextField txtTrenViaje;
    // End of variables declaration//GEN-END:variables

    /**
     * Configura el estado inicial de los componentes del diálogo.
     */
    private void configurarComponentesIniciales() {
        dchFechaSalidaViaje.setDateFormatString("dd-MM-yyyy");
        dchFechaSalidaViaje.setEnabled(false);

        configurarSpinnerHoraSalida();

        dchNacimientoPasajero.setDateFormatString("dd-MM-yyyy");
        dchNacimientoPasajero.setMaxSelectableDate(new Date());

        lblMontoPrecioBoleto.setText("$0.00");
        txtDisponibilidadViaje.setText("");
    }

    /**
     * Configura el spinner para mostrar una hora en formato HH:mm.
     */
    private void configurarSpinnerHoraSalida() {
        SpinnerDateModel modeloHora = new SpinnerDateModel();
        spnHoraSalidaViaje.setModel(modeloHora);

        JSpinner.DateEditor editor
                = new JSpinner.DateEditor(spnHoraSalidaViaje, "HH:mm");

        spnHoraSalidaViaje.setEditor(editor);
        spnHoraSalidaViaje.setEnabled(false);
    }

    /**
     * Carga los tipos de boleto disponibles y selecciona el tipo inicial.
     */
    private void cargarTiposBoleto() {
        DefaultComboBoxModel<String> modelo
                = new DefaultComboBoxModel<>();

        modelo.addElement("GENERAL");
        modelo.addElement("PRIMERA_CLASE");

        cmbTipoBoleto.setModel(modelo);

        if (tipoBoletoInicial != null
                && !tipoBoletoInicial.isBlank()) {
            cmbTipoBoleto.setSelectedItem(tipoBoletoInicial);
        } else {
            cmbTipoBoleto.setSelectedItem("GENERAL");
        }
    }

    /**
     * Carga las opciones de sexo del pasajero.
     */
    private void cargarSexosPasajero() {
        cmbSexoPasajero.removeAllItems();

        cmbSexoPasajero.addItem("Seleccionar");
        cmbSexoPasajero.addItem("MASCULINO");
        cmbSexoPasajero.addItem("FEMENINO");

        cmbSexoPasajero.setSelectedIndex(0);
    }

    /**
     * Carga en pantalla la información del viaje seleccionado.
     */
    private void cargarDatosViaje() {
        if (viajeSeleccionado == null) {
            return;
        }

        txtTrenViaje.setText(viajeSeleccionado.getTrenNombre());
        txtOrigenViaje.setText(viajeSeleccionado.getOrigen());
        txtDestinoViaje.setText(viajeSeleccionado.getDestino());

        try {
            Instant salida = Instant.parse(
                    viajeSeleccionado.getFechaHoraSalida()
            );

            Date fechaHoraSalida = Date.from(salida);

            dchFechaSalidaViaje.setDate(fechaHoraSalida);
            spnHoraSalidaViaje.setValue(fechaHoraSalida);

        } catch (Exception e) {
            dchFechaSalidaViaje.setDate(null);
        }
    }

    /**
     * Actualiza el precio y la disponibilidad visibles de acuerdo con el tipo
     * de boleto seleccionado.
     */
    private void actualizarPrecioYDisponibilidad() {
        if (viajeSeleccionado == null) {
            lblMontoPrecioBoleto.setText("$0.00");
            txtDisponibilidadViaje.setText("");
            btnConfirmarCompraBoleto.setEnabled(false);
            return;
        }

        String tipoBoleto = (String) cmbTipoBoleto.getSelectedItem();

        if (tipoBoleto == null || tipoBoleto.isBlank()) {
            lblMontoPrecioBoleto.setText("$0.00");
            txtDisponibilidadViaje.setText("");
            btnConfirmarCompraBoleto.setEnabled(false);
            return;
        }

        try {
            IBoletoServicio boletoServicio = new BoletoServicio();

            String precio = boletoServicio.consultarPrecioTipoBoleto(
                    tipoBoleto
            );

            lblMontoPrecioBoleto.setText("$" + precio);

        } catch (ServicioException e) {
            lblMontoPrecioBoleto.setText("$0.00");

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
        }

        int disponibilidad;

        if ("PRIMERA_CLASE".equals(tipoBoleto)) {
            disponibilidad = viajeSeleccionado.getDisponibilidadPrimeraClase();
        } else {
            disponibilidad = viajeSeleccionado.getDisponibilidadGeneral();
        }

        txtDisponibilidadViaje.setText(
                disponibilidad + " asientos disponibles"
        );

        btnConfirmarCompraBoleto.setEnabled(disponibilidad > 0);
    }

    /**
     * Limpia únicamente los datos capturados del pasajero.
     */
    private void limpiarDatosPasajero() {
        txtNombreCompletoPasajero.setText("");
        cmbSexoPasajero.setSelectedIndex(0);
        dchNacimientoPasajero.setDate(null);
        txtTelefonoPasajero.setText("");
        txtCorreoPasajero.setText("");
        txtDireccionCalleNumeroPasajero.setText("");
        txtDireccionColoniaPasajero.setText("");
        cmbDireccionCiudadPasajero.setSelectedItem(null);
        cmbDireccionCiudadPasajero.getEditor().setItem("");
        cmbDireccionEstadoPasajero.setSelectedItem(null);
        cmbDireccionEstadoPasajero.getEditor().setItem("");

        txtNombreCompletoPasajero.requestFocus();
    }

    /**
     * Construye el DTO de compra a partir de los datos capturados en pantalla.
     *
     * @return DTO con la información necesaria para generar el boleto.
     */
    private CompraBoletoDTO construirCompraBoletoDTO() {
        CompraBoletoDTO compraDTO = new CompraBoletoDTO();

        compraDTO.setViajeId(viajeSeleccionado.getViajeId());
        compraDTO.setTipoBoleto(
                (String) cmbTipoBoleto.getSelectedItem()
        );

        compraDTO.setNombreCompleto(
                txtNombreCompletoPasajero.getText()
        );

        compraDTO.setSexo(
                cmbSexoPasajero.getSelectedItem() != null
                ? cmbSexoPasajero.getSelectedItem().toString()
                : null
        );

        compraDTO.setFechaNacimiento(
                obtenerFechaNacimientoSeleccionada()
        );

        compraDTO.setTelefono(
                txtTelefonoPasajero.getText()
        );

        compraDTO.setCorreo(
                txtCorreoPasajero.getText()
        );

        compraDTO.setCalle(
                txtDireccionCalleNumeroPasajero.getText()
        );

        compraDTO.setColonia(
                txtDireccionColoniaPasajero.getText()
        );

        compraDTO.setCiudad(
                obtenerTextoComboEditable(cmbDireccionCiudadPasajero)
        );

        compraDTO.setEstado(
                obtenerTextoComboEditable(cmbDireccionEstadoPasajero)
        );

        return compraDTO;
    }

    /**
     * Obtiene la fecha de nacimiento seleccionada en formato yyyy-MM-dd.
     *
     * @return Fecha de nacimiento formateada o null si no fue seleccionada.
     */
    private String obtenerFechaNacimientoSeleccionada() {
        if (dchNacimientoPasajero.getDate() == null) {
            return null;
        }

        return dchNacimientoPasajero.getDate()
                .toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate()
                .format(DateTimeFormatter.ISO_LOCAL_DATE);
    }

    /**
     * Consulta nuevamente el viaje y actualiza su disponibilidad visible.
     *
     * @throws ServicioException Si ocurre un error al consultar el viaje.
     */
    private void actualizarDisponibilidadViaje() throws ServicioException {
        IViajeServicio viajeServicio = new ViajeServicio();

        ViajeDTO viajeActualizado = viajeServicio.buscarPorId(
                viajeSeleccionado.getViajeId()
        );

        if (viajeActualizado == null) {
            throw new ServicioException(
                    "No fue posible actualizar la disponibilidad del viaje."
            );
        }

        viajeSeleccionado.setDisponibilidadGeneral(
                viajeActualizado.getDisponibilidadGeneral()
        );

        viajeSeleccionado.setDisponibilidadPrimeraClase(
                viajeActualizado.getDisponibilidadPrimeraClase()
        );
    }

    /**
     * Carga las ciudades registradas previamente en pasajeros.
     */
    private void cargarCiudadesRegistradas() {
        try {
            IPasajeroServicio pasajeroServicio = new PasajeroServicio();
            List<String> ciudades = pasajeroServicio.consultarCiudadesRegistradas();

            cmbDireccionCiudadPasajero.removeAllItems();

            for (String ciudad : ciudades) {
                cmbDireccionCiudadPasajero.addItem(ciudad);
            }

            cmbDireccionCiudadPasajero.setSelectedItem(null);
            cmbDireccionCiudadPasajero.getEditor().setItem("");

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar las ciudades registradas.\n"
                    + e.getMessage(),
                    "Error al cargar ciudades",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Carga los estados registrados previamente en pasajeros.
     */
    private void cargarEstadosRegistrados() {
        try {
            IPasajeroServicio pasajeroServicio = new PasajeroServicio();
            List<String> estados = pasajeroServicio.consultarEstadosRegistrados();

            cmbDireccionEstadoPasajero.removeAllItems();

            for (String estado : estados) {
                cmbDireccionEstadoPasajero.addItem(estado);
            }

            cmbDireccionEstadoPasajero.setSelectedItem(null);
            cmbDireccionEstadoPasajero.getEditor().setItem("");

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar los estados registrados.\n"
                    + e.getMessage(),
                    "Error al cargar estados",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Obtiene el texto escrito o seleccionado en un JComboBox editable.
     *
     * @param combo Combo editable.
     * @return Texto capturado.
     */
    private String obtenerTextoComboEditable(
            javax.swing.JComboBox<String> combo) {

        Object valor = combo.getEditor().getItem();

        if (valor == null) {
            return null;
        }

        return valor.toString();
    }

}
