/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import itson.reservatrenesmongodb.dtos.BoletoDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.BoletoServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IBoletoServicio;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cmartinez
 */
public class dlgHistorialPasajero extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgHistorialPasajero.class.getName());

    private String pasajeroId;
    private String nombrePasajero;

    /**
     * Creates new form dlgHistorialPasajero
     */
    public dlgHistorialPasajero(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null, null);
    }

    /**
     * Crea el diálogo de historial para un pasajero específico.
     *
     * @param parent Ventana padre.
     * @param modal Indica si el diálogo será modal.
     * @param pasajeroId Identificador del pasajero.
     * @param nombrePasajero Nombre del pasajero.
     */
    public dlgHistorialPasajero(java.awt.Frame parent, boolean modal,
            String pasajeroId, String nombrePasajero) {
        super(parent, modal);
        initComponents();

        this.pasajeroId = pasajeroId;
        this.nombrePasajero = nombrePasajero;

        setTitle("Historial de viajes del pasajero");
        setLocationRelativeTo(parent);

        configurarTablaHistorial();
        cargarEncabezadoPasajero();
        cargarHistorialPasajero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloHistorial = new javax.swing.JLabel();
        lblPasajeroHistorial = new javax.swing.JLabel();
        lblContadorHistorial = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        scrlHistorialViajes = new javax.swing.JScrollPane();
        tblHistorialViajes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloHistorial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloHistorial.setText("Historial de viajes del pasajero");

        lblPasajeroHistorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPasajeroHistorial.setText("Pasajero:");

        lblContadorHistorial.setText("3 viajes registrados");

        btnSalir.setText("CERRAR");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContadorHistorial)
                    .addComponent(lblTituloHistorial)
                    .addComponent(lblPasajeroHistorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasajeroHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblContadorHistorial)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblHistorialViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrlHistorialViajes.setViewportView(tblHistorialViajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrlHistorialViajes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlHistorialViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgHistorialPasajero dialog = new dlgHistorialPasajero(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContadorHistorial;
    private javax.swing.JLabel lblPasajeroHistorial;
    private javax.swing.JLabel lblTituloHistorial;
    private javax.swing.JScrollPane scrlHistorialViajes;
    private javax.swing.JTable tblHistorialViajes;
    // End of variables declaration//GEN-END:variables

    /**
     * Configura las columnas de la tabla de historial de viajes.
     */
    private void configurarTablaHistorial() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "FOLIO",
                    "ORIGEN",
                    "DESTINO",
                    "TREN",
                    "FECHA Y HORA DE SALIDA",
                    "TIPO DE BOLETO",
                    "ESTATUS"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblHistorialViajes.setModel(modelo);

        tblHistorialViajes.setAutoResizeMode(
                javax.swing.JTable.AUTO_RESIZE_OFF
        );

        tblHistorialViajes.getColumnModel().getColumn(0).setPreferredWidth(120);
        tblHistorialViajes.getColumnModel().getColumn(1).setPreferredWidth(140);
        tblHistorialViajes.getColumnModel().getColumn(2).setPreferredWidth(140);
        tblHistorialViajes.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblHistorialViajes.getColumnModel().getColumn(4).setPreferredWidth(190);
        tblHistorialViajes.getColumnModel().getColumn(5).setPreferredWidth(140);
        tblHistorialViajes.getColumnModel().getColumn(6).setPreferredWidth(120);
    }

    /**
     * Muestra los datos principales del pasajero en el encabezado del diálogo.
     */
    private void cargarEncabezadoPasajero() {
        if (nombrePasajero == null || nombrePasajero.isBlank()) {
            lblPasajeroHistorial.setText("Pasajero:");
        } else {
            lblPasajeroHistorial.setText("Pasajero: " + nombrePasajero);
        }
    }

    /**
     * Carga en la tabla los boletos asociados al pasajero seleccionado.
     */
    private void cargarHistorialPasajero() {
        if (pasajeroId == null || pasajeroId.isBlank()) {
            lblContadorHistorial.setText("0 viajes registrados");
            return;
        }

        try {
            IBoletoServicio boletoServicio = new BoletoServicio();
            List<BoletoDTO> boletos
                    = boletoServicio.consultarPorPasajero(pasajeroId);

            DefaultTableModel modelo
                    = (DefaultTableModel) tblHistorialViajes.getModel();

            modelo.setRowCount(0);

            for (BoletoDTO boleto : boletos) {
                modelo.addRow(new Object[]{
                    boleto.getFolio(),
                    boleto.getOrigen(),
                    boleto.getDestino(),
                    boleto.getTren(),
                    formatearFechaHoraLocal(boleto.getFechaHoraSalida()),
                    boleto.getTipoBoleto(),
                    boleto.getEstatus()
                });
            }

            lblContadorHistorial.setText(
                    boletos.size() + " viajes registrados"
            );

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar el historial del pasajero.\n"
                    + e.getMessage(),
                    "Error al cargar historial",
                    JOptionPane.ERROR_MESSAGE
            );

            lblContadorHistorial.setText("0 viajes registrados");
        }
    }

    /**
     * Convierte una fecha ISO-8601 almacenada en UTC a fecha y hora local para
     * mostrarla en la tabla.
     *
     * @param fechaIso Fecha en formato ISO-8601.
     * @return Fecha formateada como dd-MM-yyyy HH:mm.
     */
    private String formatearFechaHoraLocal(String fechaIso) {
        if (fechaIso == null || fechaIso.isBlank()) {
            return "";
        }

        try {
            Instant instant = Instant.parse(fechaIso);
            ZonedDateTime fechaHoraLocal = instant.atZone(ZoneId.systemDefault());

            DateTimeFormatter formato
                    = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            return fechaHoraLocal.format(formato);

        } catch (DateTimeParseException e) {
            return fechaIso;
        }
    }
}
