/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import itson.reservatrenesmongodb.dtos.BoletoDTO;
import itson.reservatrenesmongodb.dtos.CancelacionBoletoDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.BoletoServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IBoletoServicio;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Afgord
 */
public class frmBuscarBoleto extends javax.swing.JPanel {

    /**
     * Boleto actualmente consultado en pantalla.
     */
    private BoletoDTO boletoConsultado;

    /**
     * Creates new form frmBuscarBoleto
     */
    public frmBuscarBoleto() {
        initComponents();

        configurarComponentesIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloBuscarBoleto = new javax.swing.JPanel();
        lblTituloBuscarBoleto = new javax.swing.JLabel();
        lblSubtituloBuscarBoleto = new javax.swing.JLabel();
        pnlBuscarBoleto = new javax.swing.JPanel();
        lblBuscarBoletoFolio = new javax.swing.JLabel();
        txtBuscarBoletoFolio = new javax.swing.JTextField();
        lblEjemploBuscarBoletoFolio = new javax.swing.JLabel();
        btnBuscarBoleto = new javax.swing.JButton();
        pnlBuscarBoletosDatos = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblBoletoFolio = new javax.swing.JLabel();
        lblBoletoPasajero = new javax.swing.JLabel();
        lblBoletoTren = new javax.swing.JLabel();
        lblBoletoOrigen = new javax.swing.JLabel();
        lblBoletoSalida = new javax.swing.JLabel();
        lblBoletoTipo = new javax.swing.JLabel();
        lblBoletoReservacion = new javax.swing.JLabel();
        txtBoletoFolio = new javax.swing.JTextField();
        txtBoletoPasajero = new javax.swing.JTextField();
        txtBoletoTren = new javax.swing.JTextField();
        txtBoletoOrigen = new javax.swing.JTextField();
        txtBoletoTipo = new javax.swing.JTextField();
        txtBoletoReservacion = new javax.swing.JTextField();
        txtBoletoSalida = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblBoletoEstatus = new javax.swing.JLabel();
        lblBoletoTelefono = new javax.swing.JLabel();
        lblBoletoDestino = new javax.swing.JLabel();
        lblBoletoPrecio = new javax.swing.JLabel();
        lblBoletoCancelacion = new javax.swing.JLabel();
        txtBoletoEstatus = new javax.swing.JTextField();
        txtBoletoTelefono = new javax.swing.JTextField();
        txtBoletoPrecio = new javax.swing.JTextField();
        txtBoletoCancelacion = new javax.swing.JTextField();
        txtBoletoDestino = new javax.swing.JTextField();
        pnlBoletoCancelarLimpiar = new javax.swing.JPanel();
        btnBoletoCancelar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        lblTituloBuscarBoleto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloBuscarBoleto.setText("Buscar boleto");

        lblSubtituloBuscarBoleto.setText("Consulte la información del boleto y cancélelo si es necesario");

        javax.swing.GroupLayout pnlTituloBuscarBoletoLayout = new javax.swing.GroupLayout(pnlTituloBuscarBoleto);
        pnlTituloBuscarBoleto.setLayout(pnlTituloBuscarBoletoLayout);
        pnlTituloBuscarBoletoLayout.setHorizontalGroup(
            pnlTituloBuscarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloBuscarBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloBuscarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloBuscarBoleto)
                    .addComponent(lblSubtituloBuscarBoleto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloBuscarBoletoLayout.setVerticalGroup(
            pnlTituloBuscarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloBuscarBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloBuscarBoleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtituloBuscarBoleto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBuscarBoletoFolio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscarBoletoFolio.setText("Folio del boleto:");

        txtBuscarBoletoFolio.addActionListener(this::txtBuscarBoletoFolioActionPerformed);

        lblEjemploBuscarBoletoFolio.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblEjemploBuscarBoletoFolio.setText("Ejemplos de folios: BOL-12345, BOL-67890");

        btnBuscarBoleto.setText("Buscar boleto");
        btnBuscarBoleto.addActionListener(this::btnBuscarBoletoActionPerformed);

        javax.swing.GroupLayout pnlBuscarBoletoLayout = new javax.swing.GroupLayout(pnlBuscarBoleto);
        pnlBuscarBoleto.setLayout(pnlBuscarBoletoLayout);
        pnlBuscarBoletoLayout.setHorizontalGroup(
            pnlBuscarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBuscarBoletoLayout.createSequentialGroup()
                        .addComponent(lblBuscarBoletoFolio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarBoletoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarBoleto))
                    .addComponent(lblEjemploBuscarBoletoFolio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBuscarBoletoLayout.setVerticalGroup(
            pnlBuscarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBuscarBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBuscarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarBoletoFolio)
                    .addComponent(txtBuscarBoletoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarBoleto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEjemploBuscarBoletoFolio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBuscarBoletosDatos.setLayout(new java.awt.GridLayout());

        lblBoletoFolio.setText("Folio: ");

        lblBoletoPasajero.setText("Pasajero: ");

        lblBoletoTren.setText("Tren: ");

        lblBoletoOrigen.setText("Origen: ");

        lblBoletoSalida.setText("Salida: ");

        lblBoletoTipo.setText("Tipo: ");

        lblBoletoReservacion.setText("Reservación: ");

        txtBoletoFolio.addActionListener(this::txtBoletoFolioActionPerformed);

        txtBoletoPasajero.addActionListener(this::txtBoletoPasajeroActionPerformed);

        txtBoletoTren.addActionListener(this::txtBoletoTrenActionPerformed);

        txtBoletoOrigen.addActionListener(this::txtBoletoOrigenActionPerformed);

        txtBoletoTipo.addActionListener(this::txtBoletoTipoActionPerformed);

        txtBoletoReservacion.addActionListener(this::txtBoletoReservacionActionPerformed);

        txtBoletoSalida.addActionListener(this::txtBoletoSalidaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBoletoFolio)
                        .addGap(38, 38, 38)
                        .addComponent(txtBoletoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBoletoReservacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBoletoReservacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBoletoPasajero)
                            .addComponent(lblBoletoTren)
                            .addComponent(lblBoletoOrigen)
                            .addComponent(lblBoletoSalida)
                            .addComponent(lblBoletoTipo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBoletoPasajero)
                            .addComponent(txtBoletoTren)
                            .addComponent(txtBoletoOrigen)
                            .addComponent(txtBoletoTipo)
                            .addComponent(txtBoletoSalida))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoFolio)
                    .addComponent(txtBoletoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoPasajero)
                    .addComponent(txtBoletoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoTren)
                    .addComponent(txtBoletoTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoOrigen)
                    .addComponent(txtBoletoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBoletoSalida)
                    .addComponent(txtBoletoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoTipo)
                    .addComponent(txtBoletoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoReservacion)
                    .addComponent(txtBoletoReservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlBuscarBoletosDatos.add(jPanel1);

        lblBoletoEstatus.setText("Estatus: ");

        lblBoletoTelefono.setText("Teléfono: ");

        lblBoletoDestino.setText("Destino: ");

        lblBoletoPrecio.setText("Precio: ");

        lblBoletoCancelacion.setText("Cancelación: ");

        txtBoletoEstatus.addActionListener(this::txtBoletoEstatusActionPerformed);

        txtBoletoTelefono.addActionListener(this::txtBoletoTelefonoActionPerformed);

        txtBoletoPrecio.addActionListener(this::txtBoletoPrecioActionPerformed);

        txtBoletoCancelacion.addActionListener(this::txtBoletoCancelacionActionPerformed);

        txtBoletoDestino.addActionListener(this::txtBoletoDestinoActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblBoletoCancelacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBoletoCancelacion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBoletoEstatus)
                            .addComponent(lblBoletoTelefono)
                            .addComponent(lblBoletoDestino)
                            .addComponent(lblBoletoPrecio))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBoletoEstatus)
                            .addComponent(txtBoletoTelefono)
                            .addComponent(txtBoletoPrecio)
                            .addComponent(txtBoletoDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoEstatus)
                    .addComponent(txtBoletoEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBoletoTelefono)
                    .addComponent(txtBoletoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoDestino)
                    .addComponent(txtBoletoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBoletoPrecio)
                    .addComponent(txtBoletoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBoletoCancelacion)
                    .addComponent(txtBoletoCancelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlBuscarBoletosDatos.add(jPanel2);

        btnBoletoCancelar.setText("Cancelar boleto");
        btnBoletoCancelar.addActionListener(this::btnBoletoCancelarActionPerformed);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        javax.swing.GroupLayout pnlBoletoCancelarLimpiarLayout = new javax.swing.GroupLayout(pnlBoletoCancelarLimpiar);
        pnlBoletoCancelarLimpiar.setLayout(pnlBoletoCancelarLimpiarLayout);
        pnlBoletoCancelarLimpiarLayout.setHorizontalGroup(
            pnlBoletoCancelarLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoletoCancelarLimpiarLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(btnBoletoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBoletoCancelarLimpiarLayout.setVerticalGroup(
            pnlBoletoCancelarLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBoletoCancelarLimpiarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBoletoCancelarLimpiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBoletoCancelar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTituloBuscarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBuscarBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBuscarBoletosDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addComponent(pnlBoletoCancelarLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloBuscarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBuscarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBuscarBoletosDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBoletoCancelarLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarBoletoFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarBoletoFolioActionPerformed
        buscarBoletoPorFolio();
    }//GEN-LAST:event_txtBuscarBoletoFolioActionPerformed

    private void txtBoletoFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoFolioActionPerformed

    private void txtBoletoPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoPasajeroActionPerformed

    private void txtBoletoTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoTrenActionPerformed

    private void txtBoletoOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoOrigenActionPerformed

    private void txtBoletoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoTipoActionPerformed

    private void txtBoletoReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoReservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoReservacionActionPerformed

    private void txtBoletoEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoEstatusActionPerformed

    private void txtBoletoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoTelefonoActionPerformed

    private void txtBoletoCancelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoCancelacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoCancelacionActionPerformed

    private void txtBoletoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoPrecioActionPerformed

    private void btnBoletoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoletoCancelarActionPerformed
        cancelarBoletoConsultado();
    }//GEN-LAST:event_btnBoletoCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtBuscarBoletoFolio.setText("");
        limpiarDatosBoleto();
        txtBuscarBoletoFolio.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarBoletoActionPerformed
        buscarBoletoPorFolio();
    }//GEN-LAST:event_btnBuscarBoletoActionPerformed

    private void txtBoletoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoDestinoActionPerformed

    private void txtBoletoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBoletoSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBoletoSalidaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoletoCancelar;
    private javax.swing.JButton btnBuscarBoleto;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBoletoCancelacion;
    private javax.swing.JLabel lblBoletoDestino;
    private javax.swing.JLabel lblBoletoEstatus;
    private javax.swing.JLabel lblBoletoFolio;
    private javax.swing.JLabel lblBoletoOrigen;
    private javax.swing.JLabel lblBoletoPasajero;
    private javax.swing.JLabel lblBoletoPrecio;
    private javax.swing.JLabel lblBoletoReservacion;
    private javax.swing.JLabel lblBoletoSalida;
    private javax.swing.JLabel lblBoletoTelefono;
    private javax.swing.JLabel lblBoletoTipo;
    private javax.swing.JLabel lblBoletoTren;
    private javax.swing.JLabel lblBuscarBoletoFolio;
    private javax.swing.JLabel lblEjemploBuscarBoletoFolio;
    private javax.swing.JLabel lblSubtituloBuscarBoleto;
    private javax.swing.JLabel lblTituloBuscarBoleto;
    private javax.swing.JPanel pnlBoletoCancelarLimpiar;
    private javax.swing.JPanel pnlBuscarBoleto;
    private javax.swing.JPanel pnlBuscarBoletosDatos;
    private javax.swing.JPanel pnlTituloBuscarBoleto;
    private javax.swing.JTextField txtBoletoCancelacion;
    private javax.swing.JTextField txtBoletoDestino;
    private javax.swing.JTextField txtBoletoEstatus;
    private javax.swing.JTextField txtBoletoFolio;
    private javax.swing.JTextField txtBoletoOrigen;
    private javax.swing.JTextField txtBoletoPasajero;
    private javax.swing.JTextField txtBoletoPrecio;
    private javax.swing.JTextField txtBoletoReservacion;
    private javax.swing.JTextField txtBoletoSalida;
    private javax.swing.JTextField txtBoletoTelefono;
    private javax.swing.JTextField txtBoletoTipo;
    private javax.swing.JTextField txtBoletoTren;
    private javax.swing.JTextField txtBuscarBoletoFolio;
    // End of variables declaration//GEN-END:variables

    /**
     * Configura el estado inicial de los componentes del formulario.
     */
    private void configurarComponentesIniciales() {
        boletoConsultado = null;

        txtBoletoFolio.setEditable(false);
        txtBoletoPasajero.setEditable(false);
        txtBoletoTren.setEditable(false);
        txtBoletoOrigen.setEditable(false);
        txtBoletoSalida.setEditable(false);
        txtBoletoTipo.setEditable(false);
        txtBoletoReservacion.setEditable(false);

        txtBoletoEstatus.setEditable(false);
        txtBoletoTelefono.setEditable(false);
        txtBoletoDestino.setEditable(false);
        txtBoletoPrecio.setEditable(false);
        txtBoletoCancelacion.setEditable(false);

        btnBoletoCancelar.setEnabled(false);

        limpiarDatosBoleto();
    }

    /**
     * Limpia los datos del boleto mostrados en pantalla.
     */
    private void limpiarDatosBoleto() {
        txtBoletoFolio.setText("");
        txtBoletoPasajero.setText("");
        txtBoletoTren.setText("");
        txtBoletoOrigen.setText("");
        txtBoletoSalida.setText("");
        txtBoletoTipo.setText("");
        txtBoletoReservacion.setText("");

        txtBoletoEstatus.setText("");
        txtBoletoTelefono.setText("");
        txtBoletoDestino.setText("");
        txtBoletoPrecio.setText("");
        txtBoletoCancelacion.setText("");

        btnBoletoCancelar.setEnabled(false);
        boletoConsultado = null;
    }

    /**
     * Busca un boleto por folio y carga sus datos en pantalla.
     */
    private void buscarBoletoPorFolio() {
        try {
            limpiarDatosBoleto();

            String folio = txtBuscarBoletoFolio.getText();

            IBoletoServicio boletoServicio = new BoletoServicio();
            BoletoDTO boleto = boletoServicio.buscarPorFolio(folio);

            if (boleto == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "No se encontró un boleto con el folio proporcionado.",
                        "Boleto no encontrado",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            boletoConsultado = boleto;
            mostrarDatosBoleto(boleto);

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }

    /**
     * Muestra en pantalla los datos del boleto consultado.
     *
     * @param boleto Boleto encontrado.
     */
    private void mostrarDatosBoleto(BoletoDTO boleto) {
        txtBoletoFolio.setText(valorSeguro(boleto.getFolio()));
        txtBoletoPasajero.setText(valorSeguro(boleto.getPasajeroNombre()));
        txtBoletoTelefono.setText(valorSeguro(boleto.getPasajeroTelefono()));

        txtBoletoTren.setText(valorSeguro(boleto.getTren()));
        txtBoletoOrigen.setText(valorSeguro(boleto.getOrigen()));
        txtBoletoDestino.setText(valorSeguro(boleto.getDestino()));

        txtBoletoSalida.setText(
                formatearFechaHoraLocal(boleto.getFechaHoraSalida())
        );

        txtBoletoTipo.setText(valorSeguro(boleto.getTipoBoleto()));
        txtBoletoPrecio.setText(formatearPrecio(boleto.getPrecio()));
        txtBoletoEstatus.setText(valorSeguro(boleto.getEstatus()));

        txtBoletoReservacion.setText(
                formatearFechaHoraLocal(boleto.getFechaReservacion())
        );

        txtBoletoCancelacion.setText(
                formatearFechaHoraLocal(boleto.getFechaCancelacion())
        );

        boolean puedeCancelar = "CONFIRMADO".equalsIgnoreCase(
                boleto.getEstatus()
        );

        btnBoletoCancelar.setEnabled(puedeCancelar);
    }

    /**
     * Devuelve un texto seguro para mostrar en pantalla.
     *
     * @param valor Valor original.
     * @return Texto no nulo.
     */
    private String valorSeguro(String valor) {
        return valor != null ? valor : "";
    }

    /**
     * Formatea el precio para mostrarlo en pantalla.
     *
     * @param precio Precio en texto.
     * @return Precio con signo de pesos.
     */
    private String formatearPrecio(String precio) {
        if (precio == null || precio.isBlank()) {
            return "";
        }

        return "$" + precio;
    }

    /**
     * Convierte una fecha ISO-8601 a formato local dd-MM-yyyy HH:mm.
     *
     * @param fechaIso Fecha en texto.
     * @return Fecha formateada o vacío si no existe.
     */
    private String formatearFechaHoraLocal(String fechaIso) {
        if (fechaIso == null || fechaIso.isBlank()) {
            return "";
        }

        try {
            Instant instant = Instant.parse(fechaIso);
            ZonedDateTime fechaHoraLocal = instant.atZone(
                    ZoneId.systemDefault()
            );

            DateTimeFormatter formato = DateTimeFormatter.ofPattern(
                    "dd-MM-yyyy HH:mm"
            );

            return fechaHoraLocal.format(formato);

        } catch (DateTimeParseException e) {
            return fechaIso;
        }
    }

    /**
     * Cancela el boleto actualmente consultado, previa confirmación del
     * usuario.
     */
    private void cancelarBoletoConsultado() {
        if (boletoConsultado == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Primero debe buscar un boleto confirmado.",
                    "Sin boleto seleccionado",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que desea cancelar el boleto "
                + boletoConsultado.getFolio() + "?",
                "Confirmar cancelación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            IBoletoServicio boletoServicio = new BoletoServicio();

            CancelacionBoletoDTO cancelacionDTO
                    = new CancelacionBoletoDTO(boletoConsultado.getFolio());

            BoletoDTO boletoCancelado
                    = boletoServicio.cancelarBoleto(cancelacionDTO);

            boletoConsultado = boletoCancelado;
            mostrarDatosBoleto(boletoCancelado);

            JOptionPane.showMessageDialog(
                    this,
                    "El boleto fue cancelado correctamente.",
                    "Cancelación exitosa",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }

}
