/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import itson.reservatrenesmongodb.dtos.LocacionDTO;
import itson.reservatrenesmongodb.dtos.ViajeDisponibleDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.LocacionServicio;
import itson.reservatrenesmongodb.servicios.implementaciones.ViajeServicio;
import itson.reservatrenesmongodb.servicios.interfaces.ILocacionServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IViajeServicio;
import java.time.Instant;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cmartinez
 */
public class frmConsultarViajes extends javax.swing.JPanel {

    /**
     * Lista de locaciones cargadas en los combos de origen y destino.
     *
     * Se conserva para obtener posteriormente el ID de la locación
     * seleccionada.
     */
    private List<LocacionDTO> locacionesDisponibles;

    /**
     * Resultados actuales de la búsqueda de viajes.
     */
    private List<ViajeDisponibleDTO> resultadosBusqueda;

    /**
     * Creates new form frmConsultarViajes
     */
    public frmConsultarViajes() {
        initComponents();
        this.locacionesDisponibles = new ArrayList<>();
        this.resultadosBusqueda = new ArrayList<>();

        configurarComponentesIniciales();
        configurarTablaResultadosViajes();
        cargarTiposBoleto();
        cargarLocaciones();
        configurarSeleccionTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloConsultarViajes = new javax.swing.JPanel();
        lblTituloConsultarViajes = new javax.swing.JLabel();
        lblSubtituloConsultarViajes = new javax.swing.JLabel();
        pnlFiltrosConsultaViajes = new javax.swing.JPanel();
        pnlOrigen = new javax.swing.JPanel();
        lblOrigenConsultaViajes = new javax.swing.JLabel();
        cmbOrigenConsultaViajes = new javax.swing.JComboBox<>();
        pnlDestino = new javax.swing.JPanel();
        lblDestinoConsultaViajes = new javax.swing.JLabel();
        cmbDestinoConsultaViajes = new javax.swing.JComboBox<>();
        pnlFechaSalida = new javax.swing.JPanel();
        lblFechaSalidaConsultaViajes = new javax.swing.JLabel();
        dchFechaSalidaConsultaViajes = new com.toedter.calendar.JDateChooser();
        pnlTipoBoleto = new javax.swing.JPanel();
        cmbTipoBoletoConsultaViajes = new javax.swing.JComboBox<>();
        lblTipoBoletoConsultaViajes = new javax.swing.JLabel();
        pnlBuscarViaje = new javax.swing.JPanel();
        btnBuscarViaje = new javax.swing.JButton();
        scrlListaConsultarViajes = new javax.swing.JScrollPane();
        tblListaConsultarViajes = new javax.swing.JTable();
        pnlComprarBoleto = new javax.swing.JPanel();
        btnComprarBoleto = new javax.swing.JButton();
        pnlResultadoBusqueda = new javax.swing.JPanel();
        lblResultadosBusqueda = new javax.swing.JLabel();
        lblContadorResultadosViajes = new javax.swing.JLabel();

        lblTituloConsultarViajes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloConsultarViajes.setText("Consultar viajes");

        lblSubtituloConsultarViajes.setText("Busca y selecciona tu viaje ideal");

        javax.swing.GroupLayout pnlTituloConsultarViajesLayout = new javax.swing.GroupLayout(pnlTituloConsultarViajes);
        pnlTituloConsultarViajes.setLayout(pnlTituloConsultarViajesLayout);
        pnlTituloConsultarViajesLayout.setHorizontalGroup(
            pnlTituloConsultarViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloConsultarViajesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloConsultarViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloConsultarViajes)
                    .addComponent(lblSubtituloConsultarViajes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloConsultarViajesLayout.setVerticalGroup(
            pnlTituloConsultarViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloConsultarViajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloConsultarViajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloConsultarViajes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFiltrosConsultaViajes.setLayout(new java.awt.GridLayout());

        lblOrigenConsultaViajes.setText("Origen:");

        cmbOrigenConsultaViajes.addActionListener(this::cmbOrigenConsultaViajesActionPerformed);

        javax.swing.GroupLayout pnlOrigenLayout = new javax.swing.GroupLayout(pnlOrigen);
        pnlOrigen.setLayout(pnlOrigenLayout);
        pnlOrigenLayout.setHorizontalGroup(
            pnlOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrigenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrigenConsultaViajes)
                    .addComponent(cmbOrigenConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOrigenLayout.setVerticalGroup(
            pnlOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrigenConsultaViajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbOrigenConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlFiltrosConsultaViajes.add(pnlOrigen);

        lblDestinoConsultaViajes.setText("Destino:");

        cmbDestinoConsultaViajes.addActionListener(this::cmbDestinoConsultaViajesActionPerformed);

        javax.swing.GroupLayout pnlDestinoLayout = new javax.swing.GroupLayout(pnlDestino);
        pnlDestino.setLayout(pnlDestinoLayout);
        pnlDestinoLayout.setHorizontalGroup(
            pnlDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDestinoConsultaViajes)
                    .addComponent(cmbDestinoConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDestinoLayout.setVerticalGroup(
            pnlDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDestinoConsultaViajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDestinoConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlFiltrosConsultaViajes.add(pnlDestino);

        lblFechaSalidaConsultaViajes.setText("Fecha de salida:");

        javax.swing.GroupLayout pnlFechaSalidaLayout = new javax.swing.GroupLayout(pnlFechaSalida);
        pnlFechaSalida.setLayout(pnlFechaSalidaLayout);
        pnlFechaSalidaLayout.setHorizontalGroup(
            pnlFechaSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechaSalidaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlFechaSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaSalidaConsultaViajes)
                    .addComponent(dchFechaSalidaConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFechaSalidaLayout.setVerticalGroup(
            pnlFechaSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFechaSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaSalidaConsultaViajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dchFechaSalidaConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlFiltrosConsultaViajes.add(pnlFechaSalida);

        cmbTipoBoletoConsultaViajes.addActionListener(this::cmbTipoBoletoConsultaViajesActionPerformed);

        lblTipoBoletoConsultaViajes.setText("Tipo de boleto:");

        javax.swing.GroupLayout pnlTipoBoletoLayout = new javax.swing.GroupLayout(pnlTipoBoleto);
        pnlTipoBoleto.setLayout(pnlTipoBoletoLayout);
        pnlTipoBoletoLayout.setHorizontalGroup(
            pnlTipoBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoBoletoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlTipoBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoBoletoConsultaViajes)
                    .addComponent(cmbTipoBoletoConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTipoBoletoLayout.setVerticalGroup(
            pnlTipoBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipoBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoBoletoConsultaViajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipoBoletoConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlFiltrosConsultaViajes.add(pnlTipoBoleto);

        btnBuscarViaje.setText("Buscar viajes");
        btnBuscarViaje.addActionListener(this::btnBuscarViajeActionPerformed);

        javax.swing.GroupLayout pnlBuscarViajeLayout = new javax.swing.GroupLayout(pnlBuscarViaje);
        pnlBuscarViaje.setLayout(pnlBuscarViajeLayout);
        pnlBuscarViajeLayout.setHorizontalGroup(
            pnlBuscarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarViajeLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(btnBuscarViaje)
                .addGap(42, 42, 42))
        );
        pnlBuscarViajeLayout.setVerticalGroup(
            pnlBuscarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuscarViajeLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnBuscarViaje)
                .addGap(23, 23, 23))
        );

        pnlFiltrosConsultaViajes.add(pnlBuscarViaje);

        tblListaConsultarViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrlListaConsultarViajes.setViewportView(tblListaConsultarViajes);

        btnComprarBoleto.setText("Comprar boleto");
        btnComprarBoleto.addActionListener(this::btnComprarBoletoActionPerformed);

        javax.swing.GroupLayout pnlComprarBoletoLayout = new javax.swing.GroupLayout(pnlComprarBoleto);
        pnlComprarBoleto.setLayout(pnlComprarBoletoLayout);
        pnlComprarBoletoLayout.setHorizontalGroup(
            pnlComprarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlComprarBoletoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
        pnlComprarBoletoLayout.setVerticalGroup(
            pnlComprarBoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprarBoletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnComprarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblResultadosBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResultadosBusqueda.setText("Resultados de búsqueda");

        lblContadorResultadosViajes.setText("0 viajes disponibles");

        javax.swing.GroupLayout pnlResultadoBusquedaLayout = new javax.swing.GroupLayout(pnlResultadoBusqueda);
        pnlResultadoBusqueda.setLayout(pnlResultadoBusquedaLayout);
        pnlResultadoBusquedaLayout.setHorizontalGroup(
            pnlResultadoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoBusquedaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlResultadoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContadorResultadosViajes)
                    .addComponent(lblResultadosBusqueda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResultadoBusquedaLayout.setVerticalGroup(
            pnlResultadoBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblResultadosBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContadorResultadosViajes)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlComprarBoleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTituloConsultarViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlResultadoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scrlListaConsultarViajes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlFiltrosConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloConsultarViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFiltrosConsultaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlResultadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlListaConsultarViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlComprarBoleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarBoletoActionPerformed
        int filaSeleccionada = tblListaConsultarViajes.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un viaje de la tabla.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int filaModelo = tblListaConsultarViajes.convertRowIndexToModel(
                filaSeleccionada
        );

        ViajeDisponibleDTO viajeSeleccionado
                = resultadosBusqueda.get(filaModelo);

        String tipoBoletoInicial = obtenerTipoBoletoSeleccionado();

        java.awt.Window ventanaPadre
                = javax.swing.SwingUtilities.getWindowAncestor(this);

        java.awt.Frame framePadre
                = ventanaPadre instanceof java.awt.Frame
                        ? (java.awt.Frame) ventanaPadre
                        : null;

        dlgComprarBoleto dialogo = new dlgComprarBoleto(
                framePadre,
                true,
                viajeSeleccionado,
                tipoBoletoInicial
        );

        dialogo.setVisible(true);
    }//GEN-LAST:event_btnComprarBoletoActionPerformed

    private void cmbDestinoConsultaViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestinoConsultaViajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDestinoConsultaViajesActionPerformed

    private void cmbOrigenConsultaViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigenConsultaViajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrigenConsultaViajesActionPerformed

    private void cmbTipoBoletoConsultaViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoBoletoConsultaViajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoBoletoConsultaViajesActionPerformed

    private void btnBuscarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarViajeActionPerformed
        try {
            LocacionDTO origen = obtenerLocacionSeleccionada(
                    cmbOrigenConsultaViajes
            );

            LocacionDTO destino = obtenerLocacionSeleccionada(
                    cmbDestinoConsultaViajes
            );

            String origenId = origen != null ? origen.getId() : null;
            String destinoId = destino != null ? destino.getId() : null;
            String fechaSalida = obtenerFechaSalidaSeleccionada();
            String tipoBoleto = obtenerTipoBoletoSeleccionado();

            IViajeServicio viajeServicio = new ViajeServicio();

            List<ViajeDisponibleDTO> viajesDisponibles
                    = viajeServicio.consultarViajesDisponibles(
                            origenId,
                            destinoId,
                            fechaSalida,
                            tipoBoleto
                    );

            cargarResultadosBusqueda(viajesDisponibles);

        } catch (ServicioException e) {
            limpiarResultadosBusqueda();

            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_btnBuscarViajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarViaje;
    private javax.swing.JButton btnComprarBoleto;
    private javax.swing.JComboBox<String> cmbDestinoConsultaViajes;
    private javax.swing.JComboBox<String> cmbOrigenConsultaViajes;
    private javax.swing.JComboBox<String> cmbTipoBoletoConsultaViajes;
    private com.toedter.calendar.JDateChooser dchFechaSalidaConsultaViajes;
    private javax.swing.JLabel lblContadorResultadosViajes;
    private javax.swing.JLabel lblDestinoConsultaViajes;
    private javax.swing.JLabel lblFechaSalidaConsultaViajes;
    private javax.swing.JLabel lblOrigenConsultaViajes;
    private javax.swing.JLabel lblResultadosBusqueda;
    private javax.swing.JLabel lblSubtituloConsultarViajes;
    private javax.swing.JLabel lblTipoBoletoConsultaViajes;
    private javax.swing.JLabel lblTituloConsultarViajes;
    private javax.swing.JPanel pnlBuscarViaje;
    private javax.swing.JPanel pnlComprarBoleto;
    private javax.swing.JPanel pnlDestino;
    private javax.swing.JPanel pnlFechaSalida;
    private javax.swing.JPanel pnlFiltrosConsultaViajes;
    private javax.swing.JPanel pnlOrigen;
    private javax.swing.JPanel pnlResultadoBusqueda;
    private javax.swing.JPanel pnlTipoBoleto;
    private javax.swing.JPanel pnlTituloConsultarViajes;
    private javax.swing.JScrollPane scrlListaConsultarViajes;
    private javax.swing.JTable tblListaConsultarViajes;
    // End of variables declaration//GEN-END:variables

    /**
     * Configura el estado inicial de los componentes del formulario.
     */
    private void configurarComponentesIniciales() {
        dchFechaSalidaConsultaViajes.setDateFormatString("dd-MM-yyyy");
        dchFechaSalidaConsultaViajes.setMinSelectableDate(
                obtenerFechaActualSinHora()
        );

        btnComprarBoleto.setEnabled(false);

        lblContadorResultadosViajes.setText("0 viajes disponibles");
    }

    /**
     * Obtiene la fecha actual con la hora establecida en 00:00:00.
     *
     * @return Fecha actual sin hora.
     */
    private Date obtenerFechaActualSinHora() {
        return obtenerFechaSinHora(new Date());
    }

    /**
     * Elimina la información de hora de una fecha.
     *
     * @param fecha Fecha a normalizar.
     * @return Fecha con hora 00:00:00.
     */
    private Date obtenerFechaSinHora(Date fecha) {
        Calendar calendario = Calendar.getInstance();
        calendario.setTime(fecha);
        calendario.set(Calendar.HOUR_OF_DAY, 0);
        calendario.set(Calendar.MINUTE, 0);
        calendario.set(Calendar.SECOND, 0);
        calendario.set(Calendar.MILLISECOND, 0);

        return calendario.getTime();
    }

    /**
     * Carga los tipos de boleto disponibles para la búsqueda.
     */
    private void cargarTiposBoleto() {
        cmbTipoBoletoConsultaViajes.removeAllItems();

        cmbTipoBoletoConsultaViajes.addItem("Seleccionar");
        cmbTipoBoletoConsultaViajes.addItem("GENERAL");
        cmbTipoBoletoConsultaViajes.addItem("PRIMERA_CLASE");

        cmbTipoBoletoConsultaViajes.setSelectedIndex(0);
    }

    /**
     * Carga las locaciones disponibles en los combos de origen y destino.
     */
    private void cargarLocaciones() {
        try {
            ILocacionServicio locacionServicio = new LocacionServicio();

            locacionesDisponibles = locacionServicio.consultarTodas();

            cmbOrigenConsultaViajes.removeAllItems();
            cmbDestinoConsultaViajes.removeAllItems();

            cmbOrigenConsultaViajes.addItem("Seleccionar");
            cmbDestinoConsultaViajes.addItem("Seleccionar");

            for (LocacionDTO locacion : locacionesDisponibles) {
                String textoLocacion = locacion.getClave()
                        + " - "
                        + locacion.getNombre();

                cmbOrigenConsultaViajes.addItem(textoLocacion);
                cmbDestinoConsultaViajes.addItem(textoLocacion);
            }

            cmbOrigenConsultaViajes.setSelectedIndex(0);
            cmbDestinoConsultaViajes.setSelectedIndex(0);

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar las locaciones.\n"
                    + e.getMessage(),
                    "Error al cargar locaciones",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Configura las columnas de la tabla de resultados de viajes.
     *
     * La columna ID permanece oculta para utilizarla al iniciar la compra del
     * boleto.
     */
    private void configurarTablaResultadosViajes() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "ID",
                    "TREN",
                    "ORIGEN",
                    "DESTINO",
                    "FECHA Y HORA DE SALIDA",
                    "HORA LLEGADA",
                    "DISP. GENERAL",
                    "DISP. PRIMERA",
                    "ESTATUS"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblListaConsultarViajes.setModel(modelo);

        // Ocultar ID.
        tblListaConsultarViajes.getColumnModel().getColumn(0).setMinWidth(0);
        tblListaConsultarViajes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblListaConsultarViajes.getColumnModel().getColumn(0).setWidth(0);

        tblListaConsultarViajes.setAutoResizeMode(
                javax.swing.JTable.AUTO_RESIZE_OFF
        );

        tblListaConsultarViajes.getColumnModel().getColumn(1).setPreferredWidth(160);
        tblListaConsultarViajes.getColumnModel().getColumn(2).setPreferredWidth(160);
        tblListaConsultarViajes.getColumnModel().getColumn(3).setPreferredWidth(160);
        tblListaConsultarViajes.getColumnModel().getColumn(4).setPreferredWidth(200);
        tblListaConsultarViajes.getColumnModel().getColumn(5).setPreferredWidth(120);
        tblListaConsultarViajes.getColumnModel().getColumn(6).setPreferredWidth(120);
        tblListaConsultarViajes.getColumnModel().getColumn(7).setPreferredWidth(120);
        tblListaConsultarViajes.getColumnModel().getColumn(8).setPreferredWidth(120);
    }

    /**
     * Obtiene la locación seleccionada en un combo de locaciones.
     *
     * @param combo Combo de origen o destino.
     * @return Locación seleccionada o null si no hay una selección válida.
     */
    private LocacionDTO obtenerLocacionSeleccionada(
            javax.swing.JComboBox<String> combo) {

        int indiceSeleccionado = combo.getSelectedIndex();

        // Índice 0 corresponde a "Seleccionar".
        if (indiceSeleccionado <= 0) {
            return null;
        }

        return locacionesDisponibles.get(indiceSeleccionado - 1);
    }

    /**
     * Obtiene el tipo de boleto seleccionado para la búsqueda.
     *
     * @return Tipo de boleto o null si no se seleccionó uno válido.
     */
    private String obtenerTipoBoletoSeleccionado() {
        Object seleccion = cmbTipoBoletoConsultaViajes.getSelectedItem();

        if (seleccion == null
                || seleccion.toString().equalsIgnoreCase("Seleccionar")) {
            return null;
        }

        return seleccion.toString();
    }

    /**
     * Obtiene la fecha seleccionada en formato yyyy-MM-dd.
     *
     * @return Fecha formateada o null si no se seleccionó una fecha.
     */
    private String obtenerFechaSalidaSeleccionada() {
        if (dchFechaSalidaConsultaViajes.getDate() == null) {
            return null;
        }

        return dchFechaSalidaConsultaViajes.getDate()
                .toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate()
                .format(DateTimeFormatter.ISO_LOCAL_DATE);
    }

    /**
     * Carga en la tabla los viajes disponibles encontrados.
     *
     * @param viajesDisponibles Lista de viajes disponibles.
     */
    private void cargarResultadosBusqueda(
            List<ViajeDisponibleDTO> viajesDisponibles) {

        this.resultadosBusqueda = new ArrayList<>(viajesDisponibles);
        DefaultTableModel modelo
                = (DefaultTableModel) tblListaConsultarViajes.getModel();

        modelo.setRowCount(0);

        for (ViajeDisponibleDTO viaje : viajesDisponibles) {
            modelo.addRow(new Object[]{
                viaje.getViajeId(),
                viaje.getTrenNombre(),
                viaje.getOrigen(),
                viaje.getDestino(),
                formatearFechaHoraLocal(viaje.getFechaHoraSalida()),
                formatearHoraLocal(viaje.getHoraLlegada()),
                viaje.getDisponibilidadGeneral(),
                viaje.getDisponibilidadPrimeraClase(),
                viaje.getEstatus()
            });
        }

        lblContadorResultadosViajes.setText(
                viajesDisponibles.size() + " viajes disponibles"
        );

        btnComprarBoleto.setEnabled(false);
    }

    /**
     * Limpia la tabla y restablece el contador de resultados.
     */
    private void limpiarResultadosBusqueda() {
        DefaultTableModel modelo
                = (DefaultTableModel) tblListaConsultarViajes.getModel();

        modelo.setRowCount(0);
        lblContadorResultadosViajes.setText("0 viajes disponibles");
        btnComprarBoleto.setEnabled(false);
        resultadosBusqueda.clear();
    }

    /**
     * Convierte una fecha ISO-8601 a formato local dd-MM-yyyy HH:mm.
     *
     * @param fechaIso Fecha ISO-8601.
     * @return Fecha y hora formateadas.
     */
    private String formatearFechaHoraLocal(String fechaIso) {
        if (fechaIso == null || fechaIso.isBlank()) {
            return "";
        }

        try {
            Instant instant = Instant.parse(fechaIso);
            ZonedDateTime fechaHoraLocal = instant.atZone(ZoneId.systemDefault());

            DateTimeFormatter formato
                    = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            return fechaHoraLocal.format(formato);

        } catch (DateTimeParseException e) {
            return fechaIso;
        }
    }

    /**
     * Convierte una fecha ISO-8601 a hora local HH:mm.
     *
     * @param fechaIso Fecha ISO-8601.
     * @return Hora formateada.
     */
    private String formatearHoraLocal(String fechaIso) {
        if (fechaIso == null || fechaIso.isBlank()) {
            return "";
        }

        try {
            Instant instant = Instant.parse(fechaIso);
            ZonedDateTime fechaHoraLocal = instant.atZone(ZoneId.systemDefault());

            DateTimeFormatter formato
                    = DateTimeFormatter.ofPattern("HH:mm");

            return fechaHoraLocal.format(formato);

        } catch (DateTimeParseException e) {
            return fechaIso;
        }
    }

    /**
     * Habilita el botón de compra cuando el usuario selecciona un viaje.
     */
    private void configurarSeleccionTabla() {
        tblListaConsultarViajes.getSelectionModel()
                .addListSelectionListener(event -> {
                    if (!event.getValueIsAdjusting()) {
                        btnComprarBoleto.setEnabled(
                                tblListaConsultarViajes.getSelectedRow() != -1
                        );
                    }
                });
    }

}
