/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import itson.reservatrenesmongodb.dtos.DashboardDTO;
import itson.reservatrenesmongodb.dtos.ViajeDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.DashboardServicio;
import itson.reservatrenesmongodb.servicios.implementaciones.ViajeServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IDashboardServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IViajeServicio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cmartinez
 */
public class frmDashboard extends javax.swing.JPanel {

    /**
     * Creates new form frmDashboard
     */
    public frmDashboard() {
        initComponents();
        aplicarEstiloTarjetas();
        cargarResumenDashboard();
        configurarTablaProximosViajes();
        cargarProximosViajes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloDashboard = new javax.swing.JPanel();
        lblTituloDashboard = new javax.swing.JLabel();
        lblSubtituloDashboard = new javax.swing.JLabel();
        pnlContadores = new javax.swing.JPanel();
        pnlTarjetasResumen = new javax.swing.JPanel();
        pnlTarjetaViajes = new javax.swing.JPanel();
        lblViajesProgramados = new javax.swing.JLabel();
        lblContadorViajesProgramados = new javax.swing.JLabel();
        lblIconoViajesProgramados = new javax.swing.JLabel();
        pnlTarjetaBoletos = new javax.swing.JPanel();
        lblBoletosVendidos = new javax.swing.JLabel();
        lblContadorBoletosVendidos = new javax.swing.JLabel();
        lblIconoBoletosVendidos = new javax.swing.JLabel();
        pnlTarjetaTrenes = new javax.swing.JPanel();
        lblTrenesActivos = new javax.swing.JLabel();
        lblContadorTrenesActivos = new javax.swing.JLabel();
        lblIconoTrenesActivos = new javax.swing.JLabel();
        pnlTarjetaCancelaciones = new javax.swing.JPanel();
        lblCancelaciones = new javax.swing.JLabel();
        lblContadorCancelaciones = new javax.swing.JLabel();
        lblIconoCancelaciones = new javax.swing.JLabel();
        pnlProximosViajes = new javax.swing.JScrollPane();
        tblProximosViajes = new javax.swing.JTable();
        pnlTituloProximosViajes = new javax.swing.JPanel();
        lblProximosViajes = new javax.swing.JLabel();

        lblTituloDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloDashboard.setText("Dashboard");

        lblSubtituloDashboard.setText("Bienvenido al Sistema de Reservaciones de Tren");

        javax.swing.GroupLayout pnlTituloDashboardLayout = new javax.swing.GroupLayout(pnlTituloDashboard);
        pnlTituloDashboard.setLayout(pnlTituloDashboardLayout);
        pnlTituloDashboardLayout.setHorizontalGroup(
            pnlTituloDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloDashboard)
                    .addComponent(lblSubtituloDashboard))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloDashboardLayout.setVerticalGroup(
            pnlTituloDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloDashboard)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlTarjetasResumen.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        lblViajesProgramados.setText("Viajes programados");

        lblContadorViajesProgramados.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContadorViajesProgramados.setText("24");

        lblIconoViajesProgramados.setText("jLabel1");

        javax.swing.GroupLayout pnlTarjetaViajesLayout = new javax.swing.GroupLayout(pnlTarjetaViajes);
        pnlTarjetaViajes.setLayout(pnlTarjetaViajesLayout);
        pnlTarjetaViajesLayout.setHorizontalGroup(
            pnlTarjetaViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetaViajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViajesProgramados)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(pnlTarjetaViajesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblContadorViajesProgramados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIconoViajesProgramados)
                .addContainerGap())
        );
        pnlTarjetaViajesLayout.setVerticalGroup(
            pnlTarjetaViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetaViajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViajesProgramados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTarjetaViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoViajesProgramados)
                    .addComponent(lblContadorViajesProgramados))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlTarjetasResumen.add(pnlTarjetaViajes);

        lblBoletosVendidos.setText("Boletos vendidos");

        lblContadorBoletosVendidos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContadorBoletosVendidos.setText("156");

        lblIconoBoletosVendidos.setText("jLabel1");

        javax.swing.GroupLayout pnlTarjetaBoletosLayout = new javax.swing.GroupLayout(pnlTarjetaBoletos);
        pnlTarjetaBoletos.setLayout(pnlTarjetaBoletosLayout);
        pnlTarjetaBoletosLayout.setHorizontalGroup(
            pnlTarjetaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetaBoletosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTarjetaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTarjetaBoletosLayout.createSequentialGroup()
                        .addComponent(lblBoletosVendidos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlTarjetaBoletosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblContadorBoletosVendidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(lblIconoBoletosVendidos)
                        .addGap(17, 17, 17))))
        );
        pnlTarjetaBoletosLayout.setVerticalGroup(
            pnlTarjetaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetaBoletosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBoletosVendidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTarjetaBoletosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContadorBoletosVendidos)
                    .addComponent(lblIconoBoletosVendidos))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlTarjetasResumen.add(pnlTarjetaBoletos);

        lblTrenesActivos.setText("Trenes activos");

        lblContadorTrenesActivos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContadorTrenesActivos.setText("8");

        lblIconoTrenesActivos.setText("jLabel1");

        javax.swing.GroupLayout pnlTarjetaTrenesLayout = new javax.swing.GroupLayout(pnlTarjetaTrenes);
        pnlTarjetaTrenes.setLayout(pnlTarjetaTrenesLayout);
        pnlTarjetaTrenesLayout.setHorizontalGroup(
            pnlTarjetaTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetaTrenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrenesActivos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTarjetaTrenesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblContadorTrenesActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(lblIconoTrenesActivos)
                .addGap(18, 18, 18))
        );
        pnlTarjetaTrenesLayout.setVerticalGroup(
            pnlTarjetaTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetaTrenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrenesActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTarjetaTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContadorTrenesActivos)
                    .addComponent(lblIconoTrenesActivos))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlTarjetasResumen.add(pnlTarjetaTrenes);

        lblCancelaciones.setText("Cancelaciones");

        lblContadorCancelaciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblContadorCancelaciones.setText("3");

        lblIconoCancelaciones.setText("jLabel1");

        javax.swing.GroupLayout pnlTarjetaCancelacionesLayout = new javax.swing.GroupLayout(pnlTarjetaCancelaciones);
        pnlTarjetaCancelaciones.setLayout(pnlTarjetaCancelacionesLayout);
        pnlTarjetaCancelacionesLayout.setHorizontalGroup(
            pnlTarjetaCancelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetaCancelacionesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCancelaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTarjetaCancelacionesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblContadorCancelaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(lblIconoCancelaciones)
                .addGap(17, 17, 17))
        );
        pnlTarjetaCancelacionesLayout.setVerticalGroup(
            pnlTarjetaCancelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetaCancelacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCancelaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTarjetaCancelacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContadorCancelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconoCancelaciones))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlTarjetasResumen.add(pnlTarjetaCancelaciones);

        javax.swing.GroupLayout pnlContadoresLayout = new javax.swing.GroupLayout(pnlContadores);
        pnlContadores.setLayout(pnlContadoresLayout);
        pnlContadoresLayout.setHorizontalGroup(
            pnlContadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTarjetasResumen, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlContadoresLayout.setVerticalGroup(
            pnlContadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTarjetasResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblProximosViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        pnlProximosViajes.setViewportView(tblProximosViajes);

        lblProximosViajes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProximosViajes.setText("Próximos viajes");

        javax.swing.GroupLayout pnlTituloProximosViajesLayout = new javax.swing.GroupLayout(pnlTituloProximosViajes);
        pnlTituloProximosViajes.setLayout(pnlTituloProximosViajesLayout);
        pnlTituloProximosViajesLayout.setHorizontalGroup(
            pnlTituloProximosViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloProximosViajesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblProximosViajes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloProximosViajesLayout.setVerticalGroup(
            pnlTituloProximosViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloProximosViajesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProximosViajes)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlProximosViajes)
            .addComponent(pnlTituloProximosViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTituloDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTituloProximosViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProximosViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBoletosVendidos;
    private javax.swing.JLabel lblCancelaciones;
    private javax.swing.JLabel lblContadorBoletosVendidos;
    private javax.swing.JLabel lblContadorCancelaciones;
    private javax.swing.JLabel lblContadorTrenesActivos;
    private javax.swing.JLabel lblContadorViajesProgramados;
    private javax.swing.JLabel lblIconoBoletosVendidos;
    private javax.swing.JLabel lblIconoCancelaciones;
    private javax.swing.JLabel lblIconoTrenesActivos;
    private javax.swing.JLabel lblIconoViajesProgramados;
    private javax.swing.JLabel lblProximosViajes;
    private javax.swing.JLabel lblSubtituloDashboard;
    private javax.swing.JLabel lblTituloDashboard;
    private javax.swing.JLabel lblTrenesActivos;
    private javax.swing.JLabel lblViajesProgramados;
    private javax.swing.JPanel pnlContadores;
    private javax.swing.JScrollPane pnlProximosViajes;
    private javax.swing.JPanel pnlTarjetaBoletos;
    private javax.swing.JPanel pnlTarjetaCancelaciones;
    private javax.swing.JPanel pnlTarjetaTrenes;
    private javax.swing.JPanel pnlTarjetaViajes;
    private javax.swing.JPanel pnlTarjetasResumen;
    private javax.swing.JPanel pnlTituloDashboard;
    private javax.swing.JPanel pnlTituloProximosViajes;
    private javax.swing.JTable tblProximosViajes;
    // End of variables declaration//GEN-END:variables

    private void aplicarEstiloTarjetas() {
        javax.swing.border.Border borde
                = javax.swing.BorderFactory.createLineBorder(
                        new java.awt.Color(210, 210, 210)
                );

        javax.swing.border.Border margenInterno
                = javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10);

        javax.swing.border.Border bordeCompuesto
                = javax.swing.BorderFactory.createCompoundBorder(
                        borde,
                        margenInterno
                );

        pnlTarjetaViajes.setBorder(bordeCompuesto);
        pnlTarjetaBoletos.setBorder(bordeCompuesto);
        pnlTarjetaTrenes.setBorder(bordeCompuesto);
        pnlTarjetaCancelaciones.setBorder(bordeCompuesto);
    }

    /**
     * Carga los indicadores generales del dashboard desde la capa de servicios.
     */
    private void cargarResumenDashboard() {
        try {
            IDashboardServicio dashboardServicio = new DashboardServicio();
            DashboardDTO resumen = dashboardServicio.consultarResumen();

            lblContadorViajesProgramados.setText(
                    String.valueOf(resumen.getTotalViajesProgramados())
            );

            lblContadorBoletosVendidos.setText(
                    String.valueOf(resumen.getTotalBoletosConfirmados())
            );

            lblContadorTrenesActivos.setText(
                    String.valueOf(resumen.getTotalTrenesActivos())
            );

            lblContadorCancelaciones.setText(
                    String.valueOf(resumen.getTotalBoletosCancelados())
            );

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar el resumen del dashboard.\n"
                    + e.getMessage(),
                    "Error al cargar dashboard",
                    JOptionPane.ERROR_MESSAGE
            );

            lblContadorViajesProgramados.setText("0");
            lblContadorBoletosVendidos.setText("0");
            lblContadorTrenesActivos.setText("0");
            lblContadorCancelaciones.setText("0");
        }
    }

    /**
     * Configura las columnas de la tabla de próximos viajes.
     */
    private void configurarTablaProximosViajes() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "TREN",
                    "ORIGEN",
                    "DESTINO",
                    "FECHA Y HORA DE SALIDA",
                    "HORA LLEGADA",
                    "ESTATUS"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblProximosViajes.setModel(modelo);
    }

    /**
     * Carga en la tabla los próximos viajes programados.
     */
    private void cargarProximosViajes() {
        try {
            IViajeServicio viajeServicio = new ViajeServicio();
            List<ViajeDTO> viajes
                    = viajeServicio.consultarProximosViajesProgramados(4);

            DefaultTableModel modelo
                    = (DefaultTableModel) tblProximosViajes.getModel();

            modelo.setRowCount(0);

            for (ViajeDTO viaje : viajes) {
                modelo.addRow(new Object[]{
                    viaje.getTrenNombre(),
                    viaje.getOrigenNombre(),
                    viaje.getDestinoNombre(),
                    formatearFechaHora(viaje.getFechaHoraSalida()),
                    extraerHora(viaje.getFechaHoraLlegadaEstimada()),
                    viaje.getEstatus()
                });
            }

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar los próximos viajes.\n"
                    + e.getMessage(),
                    "Error al cargar viajes",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Convierte una fecha ISO-8601 a un formato sencillo para la tabla.
     *
     * Ejemplo: 2026-05-15T08:00:00Z -> 2026-05-15 08:00
     *
     * @param fechaIso Fecha en formato ISO.
     * @return Fecha formateada.
     */
    private String formatearFechaHora(String fechaIso) {
        if (fechaIso == null || fechaIso.isBlank()) {
            return "";
        }

        return fechaIso.replace("T", " ")
                .replace(":00Z", "");
    }

    /**
     * Extrae la hora de una fecha ISO-8601.
     *
     * Ejemplo: 2026-05-15T11:30:00Z -> 11:30
     *
     * @param fechaIso Fecha en formato ISO.
     * @return Hora formateada.
     */
    private String extraerHora(String fechaIso) {
        if (fechaIso == null || fechaIso.isBlank()) {
            return "";
        }

        int inicioHora = fechaIso.indexOf("T");

        if (inicioHora == -1 || fechaIso.length() < inicioHora + 6) {
            return fechaIso;
        }

        return fechaIso.substring(inicioHora + 1, inicioHora + 6);
    }

}
