/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import itson.reservatrenesmongodb.dtos.LocacionDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.LocacionServicio;
import itson.reservatrenesmongodb.servicios.interfaces.ILocacionServicio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cmartinez
 */
public class frmLocaciones extends javax.swing.JPanel {

    /**
     * Identificador de la locación que se encuentra en edición. Si es null, el
     * formulario está en modo registro.
     */
    private String idLocacionEnEdicion = null;

    /**
     * Creates new form frmLocaciones
     */
    public frmLocaciones() {
        initComponents();
        chkLocacionActiva.setSelected(true);
        configurarTablaLocaciones();
        cargarLocaciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloLocaciones = new javax.swing.JPanel();
        lblTituloLocaciones = new javax.swing.JLabel();
        lblSubtituloLocaciones = new javax.swing.JLabel();
        pnlAgregarLocacion = new javax.swing.JPanel();
        lblAgregarLocacion = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        txtClaveLocacion = new javax.swing.JTextField();
        lblNombreLocacion = new javax.swing.JLabel();
        txtNombreLocacion = new javax.swing.JTextField();
        lblEstadoLocacion = new javax.swing.JLabel();
        txtEstadoLocacion = new javax.swing.JTextField();
        lblPaisLocacion = new javax.swing.JLabel();
        txtPaisLocacion = new javax.swing.JTextField();
        chkLocacionActiva = new javax.swing.JCheckBox();
        btnAgregarLocacion = new javax.swing.JButton();
        btnLimpiarLocacion = new javax.swing.JButton();
        pnlListaLocaciones = new javax.swing.JPanel();
        lblListaLocaciones = new javax.swing.JLabel();
        lblLocacionesRegistradas = new javax.swing.JLabel();
        pnlTablaListaLocaciones = new javax.swing.JScrollPane();
        tblListaLocaciones = new javax.swing.JTable();
        pnlEditarEliminarLocacion = new javax.swing.JPanel();
        btnEditarLocacion = new javax.swing.JButton();
        btnEliminarLocacion = new javax.swing.JButton();

        lblTituloLocaciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloLocaciones.setText("Administrar locaciones");

        lblSubtituloLocaciones.setText("Gestione las estaciones y puntos de parada");

        javax.swing.GroupLayout pnlTituloLocacionesLayout = new javax.swing.GroupLayout(pnlTituloLocaciones);
        pnlTituloLocaciones.setLayout(pnlTituloLocacionesLayout);
        pnlTituloLocacionesLayout.setHorizontalGroup(
            pnlTituloLocacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLocacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloLocacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloLocaciones)
                    .addComponent(lblSubtituloLocaciones))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLocacionesLayout.setVerticalGroup(
            pnlTituloLocacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLocacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloLocaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloLocaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAgregarLocacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAgregarLocacion.setText("Agregar nueva locación");

        lblClave.setText("Clave *");

        txtClaveLocacion.addActionListener(this::txtClaveLocacionActionPerformed);

        lblNombreLocacion.setText("Nombre *");

        txtNombreLocacion.addActionListener(this::txtNombreLocacionActionPerformed);

        lblEstadoLocacion.setText("Estado *");

        txtEstadoLocacion.addActionListener(this::txtEstadoLocacionActionPerformed);

        lblPaisLocacion.setText("País *");

        txtPaisLocacion.addActionListener(this::txtPaisLocacionActionPerformed);

        chkLocacionActiva.setSelected(true);
        chkLocacionActiva.setText("Locación activa");
        chkLocacionActiva.addActionListener(this::chkLocacionActivaActionPerformed);

        btnAgregarLocacion.setText("+ Agregar");
        btnAgregarLocacion.addActionListener(this::btnAgregarLocacionActionPerformed);

        btnLimpiarLocacion.setText("Limpiar");
        btnLimpiarLocacion.addActionListener(this::btnLimpiarLocacionActionPerformed);

        javax.swing.GroupLayout pnlAgregarLocacionLayout = new javax.swing.GroupLayout(pnlAgregarLocacion);
        pnlAgregarLocacion.setLayout(pnlAgregarLocacionLayout);
        pnlAgregarLocacionLayout.setHorizontalGroup(
            pnlAgregarLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarLocacionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlAgregarLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkLocacionActiva)
                    .addComponent(lblPaisLocacion)
                    .addComponent(lblEstadoLocacion)
                    .addComponent(lblNombreLocacion)
                    .addComponent(lblClave)
                    .addComponent(lblAgregarLocacion)
                    .addComponent(txtClaveLocacion)
                    .addComponent(txtNombreLocacion, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(txtEstadoLocacion)
                    .addComponent(txtPaisLocacion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarLocacionLayout.createSequentialGroup()
                        .addComponent(btnAgregarLocacion)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarLocacion)
                        .addGap(33, 33, 33)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        pnlAgregarLocacionLayout.setVerticalGroup(
            pnlAgregarLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarLocacionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblAgregarLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClaveLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstadoLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEstadoLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaisLocacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPaisLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkLocacionActiva)
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarLocacion)
                    .addComponent(btnLimpiarLocacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblListaLocaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblListaLocaciones.setText("Lista de locaciones");

        lblLocacionesRegistradas.setText("5 locaciones registradas");

        javax.swing.GroupLayout pnlListaLocacionesLayout = new javax.swing.GroupLayout(pnlListaLocaciones);
        pnlListaLocaciones.setLayout(pnlListaLocacionesLayout);
        pnlListaLocacionesLayout.setHorizontalGroup(
            pnlListaLocacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLocacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaLocacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaLocaciones)
                    .addComponent(lblLocacionesRegistradas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListaLocacionesLayout.setVerticalGroup(
            pnlListaLocacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaLocacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaLocaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLocacionesRegistradas)
                .addContainerGap())
        );

        tblListaLocaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        pnlTablaListaLocaciones.setViewportView(tblListaLocaciones);

        btnEditarLocacion.setText("Editar");
        btnEditarLocacion.addActionListener(this::btnEditarLocacionActionPerformed);

        btnEliminarLocacion.setText("Eliminar");
        btnEliminarLocacion.addActionListener(this::btnEliminarLocacionActionPerformed);

        javax.swing.GroupLayout pnlEditarEliminarLocacionLayout = new javax.swing.GroupLayout(pnlEditarEliminarLocacion);
        pnlEditarEliminarLocacion.setLayout(pnlEditarEliminarLocacionLayout);
        pnlEditarEliminarLocacionLayout.setHorizontalGroup(
            pnlEditarEliminarLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarEliminarLocacionLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnEditarLocacion)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarLocacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEditarEliminarLocacionLayout.setVerticalGroup(
            pnlEditarEliminarLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarEliminarLocacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditarEliminarLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarLocacion)
                    .addComponent(btnEliminarLocacion))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloLocaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAgregarLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTablaListaLocaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlListaLocaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEditarEliminarLocacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTituloLocaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAgregarLocacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlListaLocaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTablaListaLocaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlEditarEliminarLocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkLocacionActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLocacionActivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLocacionActivaActionPerformed

    private void txtClaveLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveLocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveLocacionActionPerformed

    private void txtNombreLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreLocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreLocacionActionPerformed

    private void txtEstadoLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoLocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoLocacionActionPerformed

    private void txtPaisLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisLocacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisLocacionActionPerformed

    private void btnAgregarLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLocacionActionPerformed
//        try {
//            LocacionDTO locacionDTO = new LocacionDTO(
//                    txtClaveLocacion.getText(),
//                    txtNombreLocacion.getText(),
//                    txtEstadoLocacion.getText(),
//                    txtPaisLocacion.getText(),
//                    chkLocacionActiva.isSelected()
//            );
//
//            ILocacionServicio locacionServicio = new LocacionServicio();
//            locacionServicio.registrar(locacionDTO);
//
//            JOptionPane.showMessageDialog(
//                    this,
//                    "Locación registrada correctamente.",
//                    "Registro exitoso",
//                    JOptionPane.INFORMATION_MESSAGE
//            );
//
//            limpiarFormulario();
//            cargarLocaciones();
//
//        } catch (ServicioException e) {
//            JOptionPane.showMessageDialog(
//                    this,
//                    e.getMessage(),
//                    "No fue posible registrar la locación",
//                    JOptionPane.WARNING_MESSAGE
//            );
//        }

        if (idLocacionEnEdicion == null) {
            registrarLocacion();
        } else {
            actualizarLocacion();
        }

    }//GEN-LAST:event_btnAgregarLocacionActionPerformed

    private void btnLimpiarLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLocacionActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarLocacionActionPerformed

    private void btnEditarLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLocacionActionPerformed
        int filaSeleccionada = tblListaLocaciones.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una locación de la tabla para editarla.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        DefaultTableModel modelo
                = (DefaultTableModel) tblListaLocaciones.getModel();

        idLocacionEnEdicion = modelo.getValueAt(filaSeleccionada, 0).toString();

        txtClaveLocacion.setText(
                modelo.getValueAt(filaSeleccionada, 1).toString()
        );

        txtNombreLocacion.setText(
                modelo.getValueAt(filaSeleccionada, 2).toString()
        );

        txtEstadoLocacion.setText(
                modelo.getValueAt(filaSeleccionada, 3).toString()
        );

        txtPaisLocacion.setText(
                modelo.getValueAt(filaSeleccionada, 4).toString()
        );

        chkLocacionActiva.setSelected(
                "Activa".equalsIgnoreCase(
                        modelo.getValueAt(filaSeleccionada, 5).toString()
                )
        );

        lblAgregarLocacion.setText("Editar locación");
        btnAgregarLocacion.setText("Actualizar");
        txtClaveLocacion.requestFocus();
    }//GEN-LAST:event_btnEditarLocacionActionPerformed

    private void btnEliminarLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLocacionActionPerformed
        int filaSeleccionada = tblListaLocaciones.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una locación de la tabla para eliminarla.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar la locación seleccionada?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            DefaultTableModel modelo
                    = (DefaultTableModel) tblListaLocaciones.getModel();

            String idLocacion = modelo.getValueAt(filaSeleccionada, 0).toString();

            ILocacionServicio locacionServicio = new LocacionServicio();
            locacionServicio.eliminar(idLocacion);

            JOptionPane.showMessageDialog(
                    this,
                    "Locación eliminada correctamente.",
                    "Eliminación exitosa",
                    JOptionPane.INFORMATION_MESSAGE
            );

            if (idLocacion.equals(idLocacionEnEdicion)) {
                limpiarFormulario();
            }

            cargarLocaciones();

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "No fue posible eliminar la locación",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEliminarLocacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLocacion;
    private javax.swing.JButton btnEditarLocacion;
    private javax.swing.JButton btnEliminarLocacion;
    private javax.swing.JButton btnLimpiarLocacion;
    private javax.swing.JCheckBox chkLocacionActiva;
    private javax.swing.JLabel lblAgregarLocacion;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblEstadoLocacion;
    private javax.swing.JLabel lblListaLocaciones;
    private javax.swing.JLabel lblLocacionesRegistradas;
    private javax.swing.JLabel lblNombreLocacion;
    private javax.swing.JLabel lblPaisLocacion;
    private javax.swing.JLabel lblSubtituloLocaciones;
    private javax.swing.JLabel lblTituloLocaciones;
    private javax.swing.JPanel pnlAgregarLocacion;
    private javax.swing.JPanel pnlEditarEliminarLocacion;
    private javax.swing.JPanel pnlListaLocaciones;
    private javax.swing.JScrollPane pnlTablaListaLocaciones;
    private javax.swing.JPanel pnlTituloLocaciones;
    private javax.swing.JTable tblListaLocaciones;
    private javax.swing.JTextField txtClaveLocacion;
    private javax.swing.JTextField txtEstadoLocacion;
    private javax.swing.JTextField txtNombreLocacion;
    private javax.swing.JTextField txtPaisLocacion;
    // End of variables declaration//GEN-END:variables

    /**
     * Configura las columnas de la tabla de locaciones.
     *
     * La columna ID se conserva internamente para futuras operaciones de
     * edición y eliminación, pero se oculta visualmente.
     */
    private void configurarTablaLocaciones() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "ID",
                    "CLAVE",
                    "NOMBRE",
                    "ESTADO",
                    "PAÍS",
                    "ESTATUS"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblListaLocaciones.setModel(modelo);

        // Oculta visualmente la columna ID, pero sigue disponible en el modelo.
        tblListaLocaciones.getColumnModel().getColumn(0).setMinWidth(0);
        tblListaLocaciones.getColumnModel().getColumn(0).setMaxWidth(0);
        tblListaLocaciones.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * Carga las locaciones registradas en la tabla desde la capa de servicios.
     */
    private void cargarLocaciones() {
        try {
            ILocacionServicio locacionServicio = new LocacionServicio();
            List<LocacionDTO> locaciones = locacionServicio.consultarTodas();

            DefaultTableModel modelo
                    = (DefaultTableModel) tblListaLocaciones.getModel();

            modelo.setRowCount(0);

            for (LocacionDTO locacion : locaciones) {
                modelo.addRow(new Object[]{
                    locacion.getId(),
                    locacion.getClave(),
                    locacion.getNombre(),
                    locacion.getEstado(),
                    locacion.getPais(),
                    locacion.isActiva() ? "Activa" : "Inactiva"
                });
            }

            lblLocacionesRegistradas.setText(
                    locaciones.size() + " locaciones registradas"
            );

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar las locaciones.\n"
                    + e.getMessage(),
                    "Error al cargar locaciones",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Registra una nueva locación a partir de los datos del formulario.
     */
    private void registrarLocacion() {
        try {
            LocacionDTO locacionDTO = new LocacionDTO(
                    txtClaveLocacion.getText(),
                    txtNombreLocacion.getText(),
                    txtEstadoLocacion.getText(),
                    txtPaisLocacion.getText(),
                    chkLocacionActiva.isSelected()
            );

            ILocacionServicio locacionServicio = new LocacionServicio();
            locacionServicio.registrar(locacionDTO);

            JOptionPane.showMessageDialog(
                    this,
                    "Locación registrada correctamente.",
                    "Registro exitoso",
                    JOptionPane.INFORMATION_MESSAGE
            );

            limpiarFormulario();
            cargarLocaciones();

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "No fue posible registrar la locación",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }

    /**
     * Actualiza la locación que se encuentra actualmente en edición.
     */
    private void actualizarLocacion() {
        try {
            ILocacionServicio locacionServicio = new LocacionServicio();

            LocacionDTO locacionDTO = locacionServicio.buscarPorId(
                    idLocacionEnEdicion
            );

            if (locacionDTO == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "La locación seleccionada ya no existe.",
                        "Locación no encontrada",
                        JOptionPane.WARNING_MESSAGE
                );

                limpiarFormulario();
                cargarLocaciones();
                return;
            }

            locacionDTO.setClave(txtClaveLocacion.getText());
            locacionDTO.setNombre(txtNombreLocacion.getText());
            locacionDTO.setEstado(txtEstadoLocacion.getText());
            locacionDTO.setPais(txtPaisLocacion.getText());
            locacionDTO.setActiva(chkLocacionActiva.isSelected());

            locacionServicio.actualizar(locacionDTO);

            JOptionPane.showMessageDialog(
                    this,
                    "Locación actualizada correctamente.",
                    "Actualización exitosa",
                    JOptionPane.INFORMATION_MESSAGE
            );

            limpiarFormulario();
            cargarLocaciones();

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "No fue posible actualizar la locación",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }

    /**
     * Limpia los campos del formulario de locaciones.
     */
    private void limpiarFormulario() {
        txtClaveLocacion.setText("");
        txtNombreLocacion.setText("");
        txtEstadoLocacion.setText("");
        txtPaisLocacion.setText("");
        chkLocacionActiva.setSelected(true);

        idLocacionEnEdicion = null;
        lblAgregarLocacion.setText("Agregar nueva locación");
        btnAgregarLocacion.setText("+ Agregar");

        tblListaLocaciones.clearSelection();
        txtClaveLocacion.requestFocus();
    }
}
