/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import itson.reservatrenesmongodb.dtos.PasajeroDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.PasajeroServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IPasajeroServicio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cmartinez
 */
public class frmPasajeros extends javax.swing.JPanel {

    /**
     * Creates new form frmPasajeros
     */
    public frmPasajeros() {
        initComponents();
        configurarTablaPasajeros();
        cargarPasajeros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloPasajeros = new javax.swing.JPanel();
        lblTituloPasajeros = new javax.swing.JLabel();
        lblSubtituloPasajeros = new javax.swing.JLabel();
        pnlContadorPasajeros = new javax.swing.JPanel();
        lblListaPasajeros = new javax.swing.JLabel();
        lblContadorPasajeros = new javax.swing.JLabel();
        lblIconoPasajeros = new javax.swing.JLabel();
        scrlListaPasajeros = new javax.swing.JScrollPane();
        tblListaPasajeros = new javax.swing.JTable();
        pnlBotonHistorial = new javax.swing.JPanel();
        btnMostrarHistorial = new javax.swing.JButton();

        lblTituloPasajeros.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloPasajeros.setText("Pasajeros");

        lblSubtituloPasajeros.setText("Registro de pasajeros del sistema");

        javax.swing.GroupLayout pnlTituloPasajerosLayout = new javax.swing.GroupLayout(pnlTituloPasajeros);
        pnlTituloPasajeros.setLayout(pnlTituloPasajerosLayout);
        pnlTituloPasajerosLayout.setHorizontalGroup(
            pnlTituloPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloPasajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPasajeros)
                    .addComponent(lblSubtituloPasajeros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloPasajerosLayout.setVerticalGroup(
            pnlTituloPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloPasajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPasajeros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloPasajeros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblListaPasajeros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblListaPasajeros.setText("Lista de pasajeros");

        lblContadorPasajeros.setText("4 pasajeros registrados");

        javax.swing.GroupLayout pnlContadorPasajerosLayout = new javax.swing.GroupLayout(pnlContadorPasajeros);
        pnlContadorPasajeros.setLayout(pnlContadorPasajerosLayout);
        pnlContadorPasajerosLayout.setHorizontalGroup(
            pnlContadorPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContadorPasajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIconoPasajeros)
                .addGap(30, 30, 30)
                .addGroup(pnlContadorPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContadorPasajeros)
                    .addComponent(lblListaPasajeros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContadorPasajerosLayout.setVerticalGroup(
            pnlContadorPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContadorPasajerosLayout.createSequentialGroup()
                .addGroup(pnlContadorPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContadorPasajerosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblListaPasajeros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContadorPasajeros))
                    .addGroup(pnlContadorPasajerosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblIconoPasajeros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblListaPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrlListaPasajeros.setViewportView(tblListaPasajeros);

        btnMostrarHistorial.setText("Ver Historial");
        btnMostrarHistorial.addActionListener(this::btnMostrarHistorialActionPerformed);

        javax.swing.GroupLayout pnlBotonHistorialLayout = new javax.swing.GroupLayout(pnlBotonHistorial);
        pnlBotonHistorial.setLayout(pnlBotonHistorialLayout);
        pnlBotonHistorialLayout.setHorizontalGroup(
            pnlBotonHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonHistorialLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btnMostrarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        pnlBotonHistorialLayout.setVerticalGroup(
            pnlBotonHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMostrarHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotonHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTituloPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContadorPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrlListaPasajeros))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlContadorPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrlListaPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotonHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarHistorialActionPerformed
        int fila = tblListaPasajeros.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un pasajero de la tabla.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String pasajeroId = tblListaPasajeros.getValueAt(fila, 0).toString();
        String nombrePasajero = tblListaPasajeros.getValueAt(fila, 1).toString();

        java.awt.Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        java.awt.Frame framePadre = ventanaPadre instanceof java.awt.Frame
                ? (java.awt.Frame) ventanaPadre
                : null;

        dlgHistorialPasajero dialogo = new dlgHistorialPasajero(
                framePadre,
                true,
                pasajeroId,
                nombrePasajero
        );

        dialogo.setVisible(true);
    }//GEN-LAST:event_btnMostrarHistorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarHistorial;
    private javax.swing.JLabel lblContadorPasajeros;
    private javax.swing.JLabel lblIconoPasajeros;
    private javax.swing.JLabel lblListaPasajeros;
    private javax.swing.JLabel lblSubtituloPasajeros;
    private javax.swing.JLabel lblTituloPasajeros;
    private javax.swing.JPanel pnlBotonHistorial;
    private javax.swing.JPanel pnlContadorPasajeros;
    private javax.swing.JPanel pnlTituloPasajeros;
    private javax.swing.JScrollPane scrlListaPasajeros;
    private javax.swing.JTable tblListaPasajeros;
    // End of variables declaration//GEN-END:variables

    /**
     * Configura las columnas de la tabla de pasajeros.
     *
     * La columna ID se mantiene oculta para utilizarla posteriormente al
     * consultar el historial del pasajero seleccionado.
     */
    private void configurarTablaPasajeros() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "ID",
                    "NOMBRE COMPLETO",
                    "TELÉFONO",
                    "CORREO ELECTRÓNICO",
                    "CIUDAD",
                    "VIAJES REGISTRADOS"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblListaPasajeros.setModel(modelo);

        tblListaPasajeros.getColumnModel().getColumn(0).setMinWidth(0);
        tblListaPasajeros.getColumnModel().getColumn(0).setMaxWidth(0);
        tblListaPasajeros.getColumnModel().getColumn(0).setWidth(0);

        tblListaPasajeros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tblListaPasajeros.getColumnModel().getColumn(1).setPreferredWidth(220);
        tblListaPasajeros.getColumnModel().getColumn(2).setPreferredWidth(130);
        tblListaPasajeros.getColumnModel().getColumn(3).setPreferredWidth(240);
        tblListaPasajeros.getColumnModel().getColumn(4).setPreferredWidth(160);
        tblListaPasajeros.getColumnModel().getColumn(5).setPreferredWidth(160);
    }

    /**
     * Carga los pasajeros registrados en la tabla.
     */
    private void cargarPasajeros() {
        try {
            IPasajeroServicio pasajeroServicio = new PasajeroServicio();
            List<PasajeroDTO> pasajeros = pasajeroServicio.consultarTodos();

            DefaultTableModel modelo
                    = (DefaultTableModel) tblListaPasajeros.getModel();

            modelo.setRowCount(0);

            for (PasajeroDTO pasajero : pasajeros) {
                modelo.addRow(new Object[]{
                    pasajero.getId(),
                    pasajero.getNombreCompleto(),
                    pasajero.getTelefono(),
                    pasajero.getCorreo(),
                    pasajero.getCiudad(),
                    pasajero.getViajesRegistrados()
                });
            }

            lblContadorPasajeros.setText(
                    pasajeros.size() + " pasajeros registrados"
            );

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar los pasajeros.\n"
                    + e.getMessage(),
                    "Error al cargar pasajeros",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

}
