/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author cmartinez
 */
public class frmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        setTitle("Sistema de Reservaciones de Tren");
        setSize(1200, 700);
        setLocationRelativeTo(null);

        pnlContenido.setLayout(new BorderLayout());
        mostrarPanel(new frmDashboard());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuLateral = new javax.swing.JPanel();
        lblIconoTren = new javax.swing.JLabel();
        lblTituloSistema = new javax.swing.JLabel();
        lblSubtituloSistema = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnConsultarViajes = new javax.swing.JButton();
        btnComprarBoleto = new javax.swing.JButton();
        btnCancelarBoleto = new javax.swing.JButton();
        btnPasajeros = new javax.swing.JButton();
        btnTrenes = new javax.swing.JButton();
        btnLocaciones = new javax.swing.JButton();
        btnViajes = new javax.swing.JButton();
        lblIconoDashboard = new javax.swing.JLabel();
        lblIconoConsultar = new javax.swing.JLabel();
        lblIconoComprar = new javax.swing.JLabel();
        lblIconoCancelar = new javax.swing.JLabel();
        lblIconoPasajeros = new javax.swing.JLabel();
        lblIconoTrenes = new javax.swing.JLabel();
        lblIconoLocaciones = new javax.swing.JLabel();
        lblIconoViajes = new javax.swing.JLabel();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIconoTren.setText("jLabel1");

        lblTituloSistema.setText("Sistema de");

        lblSubtituloSistema.setText("Reservaciones de Trenes");

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnConsultarViajes.setText("Consultar viajes");
        btnConsultarViajes.addActionListener(this::btnConsultarViajesActionPerformed);

        btnComprarBoleto.setText("Comprar boletos");
        btnComprarBoleto.addActionListener(this::btnComprarBoletoActionPerformed);

        btnCancelarBoleto.setText("Cancelar boletos");
        btnCancelarBoleto.addActionListener(this::btnCancelarBoletoActionPerformed);

        btnPasajeros.setText("Pasajeros");
        btnPasajeros.addActionListener(this::btnPasajerosActionPerformed);

        btnTrenes.setText("Trenes");
        btnTrenes.addActionListener(this::btnTrenesActionPerformed);

        btnLocaciones.setText("Locaciones");
        btnLocaciones.addActionListener(this::btnLocacionesActionPerformed);

        btnViajes.setText("Viajes");
        btnViajes.addActionListener(this::btnViajesActionPerformed);

        lblIconoDashboard.setText("jLabel1");

        lblIconoConsultar.setText("jLabel1");

        lblIconoComprar.setText("jLabel1");

        lblIconoCancelar.setText("jLabel1");

        lblIconoPasajeros.setText("jLabel1");

        lblIconoTrenes.setText("jLabel1");

        lblIconoLocaciones.setText("jLabel1");

        lblIconoViajes.setText("jLabel1");

        javax.swing.GroupLayout pnlMenuLateralLayout = new javax.swing.GroupLayout(pnlMenuLateral);
        pnlMenuLateral.setLayout(pnlMenuLateralLayout);
        pnlMenuLateralLayout.setHorizontalGroup(
            pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconoTren)
                    .addComponent(lblIconoDashboard)
                    .addComponent(lblIconoConsultar)
                    .addComponent(lblIconoComprar)
                    .addComponent(lblIconoCancelar)
                    .addComponent(lblIconoPasajeros)
                    .addComponent(lblIconoTrenes)
                    .addComponent(lblIconoLocaciones)
                    .addComponent(lblIconoViajes))
                .addGap(18, 18, 18)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtituloSistema)
                    .addComponent(lblTituloSistema)
                    .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnConsultarViajes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprarBoleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnViajes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLocaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTrenes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPasajeros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarBoleto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlMenuLateralLayout.setVerticalGroup(
            pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLateralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIconoTren)
                    .addComponent(lblTituloSistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloSistema)
                .addGap(42, 42, 42)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDashboard)
                    .addComponent(lblIconoDashboard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarViajes)
                    .addComponent(lblIconoConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprarBoleto)
                    .addComponent(lblIconoComprar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarBoleto)
                    .addComponent(lblIconoCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPasajeros)
                    .addComponent(lblIconoPasajeros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrenes)
                    .addComponent(lblIconoTrenes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLocaciones)
                    .addComponent(lblIconoLocaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViajes)
                    .addComponent(lblIconoViajes))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarViajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarViajesActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        mostrarPanel(new frmDashboard());
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnComprarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarBoletoActionPerformed

    private void btnCancelarBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarBoletoActionPerformed

    private void btnPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPasajerosActionPerformed

    private void btnTrenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrenesActionPerformed

    private void btnLocacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocacionesActionPerformed

    private void btnViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViajesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarBoleto;
    private javax.swing.JButton btnComprarBoleto;
    private javax.swing.JButton btnConsultarViajes;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLocaciones;
    private javax.swing.JButton btnPasajeros;
    private javax.swing.JButton btnTrenes;
    private javax.swing.JButton btnViajes;
    private javax.swing.JLabel lblIconoCancelar;
    private javax.swing.JLabel lblIconoComprar;
    private javax.swing.JLabel lblIconoConsultar;
    private javax.swing.JLabel lblIconoDashboard;
    private javax.swing.JLabel lblIconoLocaciones;
    private javax.swing.JLabel lblIconoPasajeros;
    private javax.swing.JLabel lblIconoTren;
    private javax.swing.JLabel lblIconoTrenes;
    private javax.swing.JLabel lblIconoViajes;
    private javax.swing.JLabel lblSubtituloSistema;
    private javax.swing.JLabel lblTituloSistema;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlMenuLateral;
    // End of variables declaration//GEN-END:variables

    /**
     * Muestra un panel dentro del área principal de contenido.
     *
     * @param panel Panel que se desea visualizar.
     */
    private void mostrarPanel(JPanel panel) {
        pnlContenido.removeAll();
        pnlContenido.add(panel, BorderLayout.CENTER);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }

}
