/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import itson.reservatrenesmongodb.dtos.TrenDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.TrenServicio;
import itson.reservatrenesmongodb.servicios.interfaces.ITrenServicio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cmartinez
 */
public class frmTrenes extends javax.swing.JPanel {

    private String idTrenSeleccionado = null;
    private boolean modoEdicion = false;

    /**
     * Modelo visual que almacena los servicios asignados al tren durante el
     * registro o edición.
     */
    private final DefaultListModel<String> modeloServiciosTren
            = new DefaultListModel<>();

    /**
     * Creates new form frmTrenes
     */
    public frmTrenes() {
        initComponents();
        listServiciosTren.setModel(modeloServiciosTren);
        cargarServiciosDisponibles();
        configurarTablaTrenes();
        cargarTrenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloTrenes = new javax.swing.JPanel();
        lblTituloTrenes = new javax.swing.JLabel();
        lblSubtituloTrenes = new javax.swing.JLabel();
        pnlAgregarTren = new javax.swing.JPanel();
        lblAgregarTren = new javax.swing.JLabel();
        lblCodigoTren = new javax.swing.JLabel();
        txtCodigoTren = new javax.swing.JTextField();
        lblNombreTren = new javax.swing.JLabel();
        txtNombreTren = new javax.swing.JTextField();
        lblModeloTren = new javax.swing.JLabel();
        txtModeloTren = new javax.swing.JTextField();
        lblEstatusTren = new javax.swing.JLabel();
        cmbEstatusTren = new javax.swing.JComboBox<>();
        lblCapacidadGeneralTren = new javax.swing.JLabel();
        txtCapacidadGeneralTren = new javax.swing.JTextField();
        lblCapacidadPrimeraTren = new javax.swing.JLabel();
        txtCapacidadPrimeraTren = new javax.swing.JTextField();
        lblServiciosTren = new javax.swing.JLabel();
        btnAgregarTren = new javax.swing.JButton();
        btnLimpiarTren = new javax.swing.JButton();
        btnAgregarServicioTren = new javax.swing.JButton();
        scrlServiciosTren = new javax.swing.JScrollPane();
        listServiciosTren = new javax.swing.JList<>();
        btnEliminarServicio = new javax.swing.JButton();
        cmbServicioTren = new javax.swing.JComboBox<>();
        pnlListaTrenes = new javax.swing.JPanel();
        lblListaTrenes = new javax.swing.JLabel();
        lblCantidadTrenesRegistrados = new javax.swing.JLabel();
        scrlPaneListaTrenes = new javax.swing.JScrollPane();
        tblListaTrenes = new javax.swing.JTable();
        pnlEditarEliminarTren = new javax.swing.JPanel();
        btnEditarTren = new javax.swing.JButton();
        btnEliminarTren = new javax.swing.JButton();

        lblTituloTrenes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloTrenes.setText("Administrar trenes");

        lblSubtituloTrenes.setText("Gestione la flota de trenes de la empresa");

        javax.swing.GroupLayout pnlTituloTrenesLayout = new javax.swing.GroupLayout(pnlTituloTrenes);
        pnlTituloTrenes.setLayout(pnlTituloTrenesLayout);
        pnlTituloTrenesLayout.setHorizontalGroup(
            pnlTituloTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTrenesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloTrenes)
                    .addComponent(lblSubtituloTrenes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloTrenesLayout.setVerticalGroup(
            pnlTituloTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloTrenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloTrenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloTrenes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblAgregarTren.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAgregarTren.setText("Agregar nuevo tren");

        lblCodigoTren.setText("Código *");

        txtCodigoTren.addActionListener(this::txtCodigoTrenActionPerformed);

        lblNombreTren.setText("Nombre *");

        txtNombreTren.addActionListener(this::txtNombreTrenActionPerformed);

        lblModeloTren.setText("Modelo *");

        txtModeloTren.addActionListener(this::txtModeloTrenActionPerformed);

        lblEstatusTren.setText("Estatus *");

        cmbEstatusTren.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "MANTENIMIENTO", "INACTIVO" }));
        cmbEstatusTren.addActionListener(this::cmbEstatusTrenActionPerformed);

        lblCapacidadGeneralTren.setText("Capacidad General *");

        txtCapacidadGeneralTren.addActionListener(this::txtCapacidadGeneralTrenActionPerformed);

        lblCapacidadPrimeraTren.setText("Capacidad Primera Clase *");

        txtCapacidadPrimeraTren.addActionListener(this::txtCapacidadPrimeraTrenActionPerformed);

        lblServiciosTren.setText("Servicios disponibles");

        btnAgregarTren.setText("+ Agregar");
        btnAgregarTren.addActionListener(this::btnAgregarTrenActionPerformed);

        btnLimpiarTren.setText("Limpiar");
        btnLimpiarTren.addActionListener(this::btnLimpiarTrenActionPerformed);

        btnAgregarServicioTren.setText("Agregar");
        btnAgregarServicioTren.addActionListener(this::btnAgregarServicioTrenActionPerformed);

        scrlServiciosTren.setViewportView(listServiciosTren);

        btnEliminarServicio.setText("Quitar");
        btnEliminarServicio.addActionListener(this::btnEliminarServicioActionPerformed);

        cmbServicioTren.setEditable(true);

        javax.swing.GroupLayout pnlAgregarTrenLayout = new javax.swing.GroupLayout(pnlAgregarTren);
        pnlAgregarTren.setLayout(pnlAgregarTrenLayout);
        pnlAgregarTrenLayout.setHorizontalGroup(
            pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarTrenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAgregarTrenLayout.createSequentialGroup()
                        .addGroup(pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAgregarTrenLayout.createSequentialGroup()
                                .addComponent(btnAgregarTren, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarTren))
                            .addComponent(lblServiciosTren)
                            .addComponent(lblCapacidadPrimeraTren)
                            .addComponent(lblCapacidadGeneralTren)
                            .addComponent(lblEstatusTren)
                            .addComponent(lblModeloTren)
                            .addComponent(lblNombreTren)
                            .addComponent(lblCodigoTren)
                            .addComponent(lblAgregarTren)
                            .addComponent(txtCapacidadPrimeraTren)
                            .addComponent(txtCapacidadGeneralTren)
                            .addComponent(cmbEstatusTren, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtModeloTren)
                            .addComponent(txtNombreTren)
                            .addComponent(txtCodigoTren))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlAgregarTrenLayout.createSequentialGroup()
                        .addGroup(pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlServiciosTren)
                            .addComponent(cmbServicioTren, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarServicioTren, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarServicio, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnlAgregarTrenLayout.setVerticalGroup(
            pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarTrenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblAgregarTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCodigoTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblModeloTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModeloTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstatusTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEstatusTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCapacidadGeneralTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCapacidadGeneralTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCapacidadPrimeraTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCapacidadPrimeraTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblServiciosTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarServicioTren)
                    .addComponent(cmbServicioTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarTrenLayout.createSequentialGroup()
                        .addComponent(scrlServiciosTren, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAgregarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarTren)
                            .addComponent(btnLimpiarTren)))
                    .addGroup(pnlAgregarTrenLayout.createSequentialGroup()
                        .addComponent(btnEliminarServicio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblListaTrenes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblListaTrenes.setText("Lista de trenes");

        lblCantidadTrenesRegistrados.setText("4 trenes registrados");

        javax.swing.GroupLayout pnlListaTrenesLayout = new javax.swing.GroupLayout(pnlListaTrenes);
        pnlListaTrenes.setLayout(pnlListaTrenesLayout);
        pnlListaTrenesLayout.setHorizontalGroup(
            pnlListaTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaTrenesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListaTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaTrenes)
                    .addComponent(lblCantidadTrenesRegistrados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListaTrenesLayout.setVerticalGroup(
            pnlListaTrenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaTrenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaTrenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCantidadTrenesRegistrados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblListaTrenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrlPaneListaTrenes.setViewportView(tblListaTrenes);

        btnEditarTren.setText("Editar");
        btnEditarTren.addActionListener(this::btnEditarTrenActionPerformed);

        btnEliminarTren.setText("Eliminar");
        btnEliminarTren.addActionListener(this::btnEliminarTrenActionPerformed);

        javax.swing.GroupLayout pnlEditarEliminarTrenLayout = new javax.swing.GroupLayout(pnlEditarEliminarTren);
        pnlEditarEliminarTren.setLayout(pnlEditarEliminarTrenLayout);
        pnlEditarEliminarTrenLayout.setHorizontalGroup(
            pnlEditarEliminarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarEliminarTrenLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnEditarTren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarTren)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlEditarEliminarTrenLayout.setVerticalGroup(
            pnlEditarEliminarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarEliminarTrenLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlEditarEliminarTrenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarTren)
                    .addComponent(btnEliminarTren))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloTrenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAgregarTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListaTrenes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrlPaneListaTrenes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlEditarEliminarTren, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTituloTrenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAgregarTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlListaTrenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrlPaneListaTrenes, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEditarEliminarTren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstatusTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstatusTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstatusTrenActionPerformed

    private void txtCapacidadPrimeraTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadPrimeraTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadPrimeraTrenActionPerformed

    private void txtCapacidadGeneralTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadGeneralTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadGeneralTrenActionPerformed

    private void txtModeloTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloTrenActionPerformed

    private void txtNombreTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTrenActionPerformed

    private void txtCodigoTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoTrenActionPerformed

    private void btnEditarTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTrenActionPerformed
        int fila = tblListaTrenes.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un tren de la tabla.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            ITrenServicio trenServicio = new TrenServicio();

            String id = tblListaTrenes.getValueAt(fila, 0).toString(); // esto depende de si guardas el id en tabla o no
            TrenDTO tren = trenServicio.buscarPorId(id);

            idTrenSeleccionado = tren.getId();
            modoEdicion = true;

            txtCodigoTren.setText(tren.getCodigo());
            txtNombreTren.setText(tren.getNombre());
            txtModeloTren.setText(tren.getModelo());
            cmbEstatusTren.setSelectedItem(tren.getEstatus());
            txtCapacidadGeneralTren.setText(String.valueOf(tren.getCapacidadGeneral()));
            txtCapacidadPrimeraTren.setText(String.valueOf(tren.getCapacidadPrimeraClase()));

            modeloServiciosTren.clear();
            for (String servicio : tren.getServicios()) {
                modeloServiciosTren.addElement(servicio);
            }

            btnAgregarTren.setText("Actualizar");

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarTrenActionPerformed

    private void btnEliminarTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTrenActionPerformed
        int fila = tblListaTrenes.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un tren de la tabla.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Desea eliminar el tren seleccionado?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            ITrenServicio trenServicio = new TrenServicio();

            String codigo = tblListaTrenes.getValueAt(fila, 0).toString();
            trenServicio.eliminar(codigo);

            JOptionPane.showMessageDialog(this,
                    "Tren eliminado correctamente.",
                    "Eliminación exitosa",
                    JOptionPane.INFORMATION_MESSAGE);

            cargarTrenes();
            cargarServiciosDisponibles();
            limpiarFormulario();

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarTrenActionPerformed

    private void btnAgregarTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTrenActionPerformed
        if (!validarFormulario()) {
            return;
        }

        try {
            ITrenServicio trenServicio = new TrenServicio();

            TrenDTO trenDTO = new TrenDTO();
            trenDTO.setCodigo(txtCodigoTren.getText().trim());
            trenDTO.setNombre(txtNombreTren.getText().trim());
            trenDTO.setModelo(txtModeloTren.getText().trim());
            trenDTO.setEstatus(cmbEstatusTren.getSelectedItem().toString());
            trenDTO.setCapacidadGeneral(Integer.parseInt(txtCapacidadGeneralTren.getText().trim()));
            trenDTO.setCapacidadPrimeraClase(Integer.parseInt(txtCapacidadPrimeraTren.getText().trim()));
            trenDTO.setServicios(obtenerServiciosTren());

            if (!modoEdicion) {
                trenServicio.registrar(trenDTO);

                JOptionPane.showMessageDialog(this,
                        "Tren registrado correctamente.",
                        "Registro exitoso",
                        JOptionPane.INFORMATION_MESSAGE);

            } else {
                trenDTO.setId(idTrenSeleccionado);
                trenServicio.actualizar(trenDTO);

                JOptionPane.showMessageDialog(this,
                        "Tren actualizado correctamente.",
                        "Actualización exitosa",
                        JOptionPane.INFORMATION_MESSAGE);
            }

            cargarTrenes();
            cargarServiciosDisponibles();
            limpiarFormulario();

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarTrenActionPerformed

    private void btnLimpiarTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarTrenActionPerformed

    private void btnAgregarServicioTrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioTrenActionPerformed
        Object itemSeleccionado = cmbServicioTren.getEditor().getItem();

        String servicio = itemSeleccionado == null
                ? ""
                : itemSeleccionado.toString().trim();

        if (servicio.isBlank()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione o escriba un servicio antes de agregarlo.",
                    "Servicio vacío",
                    JOptionPane.WARNING_MESSAGE
            );
            cmbServicioTren.requestFocus();
            return;
        }

        for (int i = 0; i < modeloServiciosTren.size(); i++) {
            if (modeloServiciosTren.getElementAt(i).equalsIgnoreCase(servicio)) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ese servicio ya fue agregado al tren.",
                        "Servicio duplicado",
                        JOptionPane.WARNING_MESSAGE
                );
                cmbServicioTren.requestFocus();
                return;
            }
        }

        modeloServiciosTren.addElement(servicio);
        cmbServicioTren.setSelectedItem(null);
        cmbServicioTren.requestFocus();
    }//GEN-LAST:event_btnAgregarServicioTrenActionPerformed

    private void btnEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarServicioActionPerformed
        int indiceSeleccionado = listServiciosTren.getSelectedIndex();

        if (indiceSeleccionado == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un servicio de la lista para quitarlo.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        modeloServiciosTren.remove(indiceSeleccionado);
    }//GEN-LAST:event_btnEliminarServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServicioTren;
    private javax.swing.JButton btnAgregarTren;
    private javax.swing.JButton btnEditarTren;
    private javax.swing.JButton btnEliminarServicio;
    private javax.swing.JButton btnEliminarTren;
    private javax.swing.JButton btnLimpiarTren;
    private javax.swing.JComboBox<String> cmbEstatusTren;
    private javax.swing.JComboBox<String> cmbServicioTren;
    private javax.swing.JLabel lblAgregarTren;
    private javax.swing.JLabel lblCantidadTrenesRegistrados;
    private javax.swing.JLabel lblCapacidadGeneralTren;
    private javax.swing.JLabel lblCapacidadPrimeraTren;
    private javax.swing.JLabel lblCodigoTren;
    private javax.swing.JLabel lblEstatusTren;
    private javax.swing.JLabel lblListaTrenes;
    private javax.swing.JLabel lblModeloTren;
    private javax.swing.JLabel lblNombreTren;
    private javax.swing.JLabel lblServiciosTren;
    private javax.swing.JLabel lblSubtituloTrenes;
    private javax.swing.JLabel lblTituloTrenes;
    private javax.swing.JList<String> listServiciosTren;
    private javax.swing.JPanel pnlAgregarTren;
    private javax.swing.JPanel pnlEditarEliminarTren;
    private javax.swing.JPanel pnlListaTrenes;
    private javax.swing.JPanel pnlTituloTrenes;
    private javax.swing.JScrollPane scrlPaneListaTrenes;
    private javax.swing.JScrollPane scrlServiciosTren;
    private javax.swing.JTable tblListaTrenes;
    private javax.swing.JTextField txtCapacidadGeneralTren;
    private javax.swing.JTextField txtCapacidadPrimeraTren;
    private javax.swing.JTextField txtCodigoTren;
    private javax.swing.JTextField txtModeloTren;
    private javax.swing.JTextField txtNombreTren;
    // End of variables declaration//GEN-END:variables

    /**
     * Configura las columnas de la tabla de trenes.
     *
     * La columna ID se mantiene oculta para usarla después en edición y
     * eliminación.
     */
    private void configurarTablaTrenes() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "ID",
                    "CÓDIGO",
                    "NOMBRE",
                    "MODELO",
                    "ESTATUS",
                    "CAP. GENERAL",
                    "CAP. PRIMERA",
                    "SERVICIOS"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblListaTrenes.setModel(modelo);

        tblListaTrenes.getColumnModel().getColumn(0).setMinWidth(0);
        tblListaTrenes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblListaTrenes.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * Carga los trenes registrados en la tabla.
     */
    private void cargarTrenes() {
        try {
            ITrenServicio trenServicio = new TrenServicio();
            List<TrenDTO> trenes = trenServicio.consultarTodos();

            DefaultTableModel modelo
                    = (DefaultTableModel) tblListaTrenes.getModel();

            modelo.setRowCount(0);

            for (TrenDTO tren : trenes) {
                modelo.addRow(new Object[]{
                    tren.getId(),
                    tren.getCodigo(),
                    tren.getNombre(),
                    tren.getModelo(),
                    tren.getEstatus(),
                    tren.getCapacidadGeneral(),
                    tren.getCapacidadPrimeraClase(),
                    String.join(", ", tren.getServicios())
                });
            }

            lblCantidadTrenesRegistrados.setText(
                    trenes.size() + " trenes registrados"
            );

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar los trenes.\n"
                    + e.getMessage(),
                    "Error al cargar trenes",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Carga en el combo los servicios previamente registrados en otros trenes.
     */
    private void cargarServiciosDisponibles() {
        try {
            ITrenServicio trenServicio = new TrenServicio();
            List<String> servicios = trenServicio.consultarServiciosDisponibles();

            DefaultComboBoxModel<String> modeloCombo
                    = new DefaultComboBoxModel<>();

            for (String servicio : servicios) {
                modeloCombo.addElement(servicio);
            }

            cmbServicioTren.setModel(modeloCombo);
            cmbServicioTren.setSelectedItem(null);

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar los servicios disponibles.\n"
                    + e.getMessage(),
                    "Error al cargar servicios",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Obtiene los servicios asignados al tren desde la lista visual.
     *
     * @return Lista de servicios capturados.
     */
    private List<String> obtenerServiciosTren() {
        List<String> servicios = new ArrayList<>();

        for (int i = 0; i < modeloServiciosTren.size(); i++) {
            servicios.add(modeloServiciosTren.getElementAt(i));
        }

        return servicios;
    }

    private void limpiarFormulario() {
        txtCodigoTren.setText("");
        txtNombreTren.setText("");
        txtModeloTren.setText("");
        cmbEstatusTren.setSelectedIndex(0);
        txtCapacidadGeneralTren.setText("");
        txtCapacidadPrimeraTren.setText("");
        modeloServiciosTren.clear();
        cmbServicioTren.setSelectedItem(null);

        idTrenSeleccionado = null;
        modoEdicion = false;
        btnAgregarTren.setText("+ Agregar");
    }

    private boolean validarFormulario() {
        if (txtCodigoTren.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Debe capturar el código del tren.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            txtCodigoTren.requestFocus();
            return false;
        }

        if (txtNombreTren.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Debe capturar el nombre del tren.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            txtNombreTren.requestFocus();
            return false;
        }

        if (txtModeloTren.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Debe capturar el modelo del tren.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            txtModeloTren.requestFocus();
            return false;
        }

        if (txtCapacidadGeneralTren.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Debe capturar la capacidad general.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            txtCapacidadGeneralTren.requestFocus();
            return false;
        }

        if (txtCapacidadPrimeraTren.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Debe capturar la capacidad de primera clase.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            txtCapacidadPrimeraTren.requestFocus();
            return false;
        }

        try {
            int capacidadGeneral = Integer.parseInt(txtCapacidadGeneralTren.getText().trim());
            int capacidadPrimera = Integer.parseInt(txtCapacidadPrimeraTren.getText().trim());

            if (capacidadGeneral <= 0) {
                JOptionPane.showMessageDialog(this,
                        "La capacidad general debe ser mayor a cero.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                txtCapacidadGeneralTren.requestFocus();
                return false;
            }

            if (capacidadPrimera < 0) {
                JOptionPane.showMessageDialog(this,
                        "La capacidad de primera clase no puede ser negativa.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                txtCapacidadPrimeraTren.requestFocus();
                return false;
            }

            if (capacidadPrimera > capacidadGeneral) {
                JOptionPane.showMessageDialog(this,
                        "La capacidad de primera clase no puede ser mayor que la capacidad general.",
                        "Validación",
                        JOptionPane.WARNING_MESSAGE);
                txtCapacidadPrimeraTren.requestFocus();
                return false;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Las capacidades deben ser numéricas.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (modeloServiciosTren.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe agregar al menos un servicio.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
            cmbServicioTren.requestFocus();
            return false;
        }

        return true;
    }

}
