/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.reservatrenesmongodb.presentacion.frm;

import com.toedter.calendar.JDateChooser;
import itson.reservatrenesmongodb.dominio.enums.EstatusViaje;
import itson.reservatrenesmongodb.dtos.LocacionDTO;
import itson.reservatrenesmongodb.dtos.TrenDTO;
import itson.reservatrenesmongodb.dtos.ViajeDTO;
import itson.reservatrenesmongodb.exceptions.ServicioException;
import itson.reservatrenesmongodb.servicios.implementaciones.LocacionServicio;
import itson.reservatrenesmongodb.servicios.implementaciones.TrenServicio;
import itson.reservatrenesmongodb.servicios.implementaciones.ViajeServicio;
import itson.reservatrenesmongodb.servicios.interfaces.ILocacionServicio;
import itson.reservatrenesmongodb.servicios.interfaces.ITrenServicio;
import itson.reservatrenesmongodb.servicios.interfaces.IViajeServicio;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cmartinez
 */
public class frmViajes extends javax.swing.JPanel {

    private String idViajeSeleccionado = null;
    private boolean modoEdicion = false;

    /**
     * Lista de trenes disponibles para programar viajes. Se mantiene
     * sincronizada con el combo de trenes.
     */
    private final List<TrenDTO> trenesDisponibles = new ArrayList<>();

    /**
     * Lista de locaciones disponibles para origen y destino. Se mantiene
     * sincronizada con ambos combos.
     */
    private final List<LocacionDTO> locacionesDisponibles = new ArrayList<>();

    /**
     * Creates new form frmViajes
     */
    public frmViajes() {
        initComponents();
        configurarComponentesFechaHora();
        cargarEstatusViajes();
        cargarTrenesDisponibles();
        cargarLocacionesDisponibles();
        configurarTablaViajes();
        cargarViajes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloViajes = new javax.swing.JPanel();
        lblTituloViajes = new javax.swing.JLabel();
        lblSubtituloViajes = new javax.swing.JLabel();
        pnlProgramarViaje = new javax.swing.JPanel();
        lblProgramarNuevoViaje = new javax.swing.JLabel();
        lblTren = new javax.swing.JLabel();
        cmbTrenViaje = new javax.swing.JComboBox<>();
        lblOrigen = new javax.swing.JLabel();
        cmbOrigenViaje = new javax.swing.JComboBox<>();
        lblDestino = new javax.swing.JLabel();
        cmbDestinoViaje = new javax.swing.JComboBox<>();
        lblEstatus = new javax.swing.JLabel();
        cmbEstatusViaje = new javax.swing.JComboBox<>();
        lblFechaSalida = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        lblFechaEstimadaLlegada = new javax.swing.JLabel();
        lblHoraEstimadaLlegada = new javax.swing.JLabel();
        lblCapacidadMaxGeneral = new javax.swing.JLabel();
        txtCapacidadMaxGeneralViaje = new javax.swing.JTextField();
        lblCapacidadMaxPrimera = new javax.swing.JLabel();
        txtCapacidadMaxPrimeraViaje = new javax.swing.JTextField();
        lblDisponibilidadGeneral = new javax.swing.JLabel();
        txtDisponibilidadGeneralViaje = new javax.swing.JTextField();
        lblDisponibilidadPrimera = new javax.swing.JLabel();
        txtDisponibilidadPrimeraViaje = new javax.swing.JTextField();
        btnProgramarViaje = new javax.swing.JButton();
        btnLimpiarViaje = new javax.swing.JButton();
        dchFechaSalidaViaje = new com.toedter.calendar.JDateChooser();
        dchFechaLlegadaViaje = new com.toedter.calendar.JDateChooser();
        spnHoraSalidaViaje = new javax.swing.JSpinner();
        spnHoraLlegadaViaje = new javax.swing.JSpinner();
        pnlListaViajes = new javax.swing.JPanel();
        lblListaViajes = new javax.swing.JLabel();
        lblViajesProgramados = new javax.swing.JLabel();
        pnlEditarEliminarViaje = new javax.swing.JPanel();
        btnEditarViaje = new javax.swing.JButton();
        btnEliminarViaje = new javax.swing.JButton();
        scrlListaViajes = new javax.swing.JScrollPane();
        tblListaViajes = new javax.swing.JTable();

        lblTituloViajes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloViajes.setText("Administrar viajes");

        lblSubtituloViajes.setText("Programe y gestione los viajes de la empresa");

        javax.swing.GroupLayout pnlTituloViajesLayout = new javax.swing.GroupLayout(pnlTituloViajes);
        pnlTituloViajes.setLayout(pnlTituloViajesLayout);
        pnlTituloViajesLayout.setHorizontalGroup(
            pnlTituloViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloViajesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlTituloViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtituloViajes)
                    .addComponent(lblTituloViajes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloViajesLayout.setVerticalGroup(
            pnlTituloViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloViajesLayout.createSequentialGroup()
                .addComponent(lblTituloViajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtituloViajes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblProgramarNuevoViaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProgramarNuevoViaje.setText("Programar nuevo viaje ");

        lblTren.setText("Tren *");

        cmbTrenViaje.addActionListener(this::cmbTrenViajeActionPerformed);

        lblOrigen.setText("Origen *");

        cmbOrigenViaje.addActionListener(this::cmbOrigenViajeActionPerformed);

        lblDestino.setText("Destino *");

        cmbDestinoViaje.addActionListener(this::cmbDestinoViajeActionPerformed);

        lblEstatus.setText("Estatus *");

        cmbEstatusViaje.addActionListener(this::cmbEstatusViajeActionPerformed);

        lblFechaSalida.setText("Fecha de salida *");

        lblHoraSalida.setText("Hora de salida *");

        lblFechaEstimadaLlegada.setText("Fecha estimada llegada *");

        lblHoraEstimadaLlegada.setText("Hora estimada llegada *");

        lblCapacidadMaxGeneral.setText("Cap. máx. General *");

        txtCapacidadMaxGeneralViaje.setEditable(false);
        txtCapacidadMaxGeneralViaje.addActionListener(this::txtCapacidadMaxGeneralViajeActionPerformed);

        lblCapacidadMaxPrimera.setText("Cap. máx. Primera *");

        txtCapacidadMaxPrimeraViaje.setEditable(false);
        txtCapacidadMaxPrimeraViaje.addActionListener(this::txtCapacidadMaxPrimeraViajeActionPerformed);

        lblDisponibilidadGeneral.setText("Disp. General *");

        txtDisponibilidadGeneralViaje.setEditable(false);
        txtDisponibilidadGeneralViaje.addActionListener(this::txtDisponibilidadGeneralViajeActionPerformed);

        lblDisponibilidadPrimera.setText("Disp. Primera *");

        txtDisponibilidadPrimeraViaje.setEditable(false);
        txtDisponibilidadPrimeraViaje.addActionListener(this::txtDisponibilidadPrimeraViajeActionPerformed);

        btnProgramarViaje.setText("+ Programar viaje");
        btnProgramarViaje.addActionListener(this::btnProgramarViajeActionPerformed);

        btnLimpiarViaje.setText("Limpiar");
        btnLimpiarViaje.addActionListener(this::btnLimpiarViajeActionPerformed);

        javax.swing.GroupLayout pnlProgramarViajeLayout = new javax.swing.GroupLayout(pnlProgramarViaje);
        pnlProgramarViaje.setLayout(pnlProgramarViajeLayout);
        pnlProgramarViajeLayout.setHorizontalGroup(
            pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramarViajeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProgramarNuevoViaje)
                    .addGroup(pnlProgramarViajeLayout.createSequentialGroup()
                        .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnProgramarViaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCapacidadMaxGeneralViaje, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTren)
                                        .addComponent(cmbTrenViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFechaSalida)))
                                .addComponent(lblCapacidadMaxGeneral))
                            .addComponent(dchFechaSalidaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProgramarViajeLayout.createSequentialGroup()
                                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCapacidadMaxPrimeraViaje)
                                    .addComponent(lblOrigen)
                                    .addComponent(cmbOrigenViaje, 0, 154, Short.MAX_VALUE)
                                    .addComponent(lblHoraSalida)
                                    .addComponent(lblCapacidadMaxPrimera)
                                    .addComponent(spnHoraSalidaViaje))
                                .addGap(18, 18, 18)
                                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDisponibilidadGeneralViaje)
                                    .addComponent(lblDestino)
                                    .addComponent(cmbDestinoViaje, 0, 155, Short.MAX_VALUE)
                                    .addComponent(lblFechaEstimadaLlegada)
                                    .addComponent(lblDisponibilidadGeneral)
                                    .addComponent(dchFechaLlegadaViaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDisponibilidadPrimera)
                                    .addComponent(lblHoraEstimadaLlegada)
                                    .addComponent(lblEstatus)
                                    .addComponent(cmbEstatusViaje, 0, 155, Short.MAX_VALUE)
                                    .addComponent(txtDisponibilidadPrimeraViaje)
                                    .addComponent(spnHoraLlegadaViaje)))
                            .addComponent(btnLimpiarViaje))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProgramarViajeLayout.setVerticalGroup(
            pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramarViajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProgramarNuevoViaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlProgramarViajeLayout.createSequentialGroup()
                        .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTren)
                            .addComponent(lblOrigen)
                            .addComponent(lblDestino)
                            .addComponent(lblEstatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTrenViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbOrigenViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDestinoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstatusViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaSalida)
                            .addComponent(lblHoraSalida)
                            .addComponent(lblFechaEstimadaLlegada)
                            .addComponent(lblHoraEstimadaLlegada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dchFechaSalidaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnHoraSalidaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spnHoraLlegadaViaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dchFechaLlegadaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacidadMaxGeneral)
                    .addComponent(lblCapacidadMaxPrimera)
                    .addComponent(lblDisponibilidadGeneral)
                    .addComponent(lblDisponibilidadPrimera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacidadMaxGeneralViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidadMaxPrimeraViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisponibilidadGeneralViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDisponibilidadPrimeraViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProgramarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProgramarViaje)
                    .addComponent(btnLimpiarViaje))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lblListaViajes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblListaViajes.setText("Lista de viajes");

        lblViajesProgramados.setText("4 viajes programados");

        javax.swing.GroupLayout pnlListaViajesLayout = new javax.swing.GroupLayout(pnlListaViajes);
        pnlListaViajes.setLayout(pnlListaViajesLayout);
        pnlListaViajesLayout.setHorizontalGroup(
            pnlListaViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaViajesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlListaViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViajesProgramados)
                    .addComponent(lblListaViajes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListaViajesLayout.setVerticalGroup(
            pnlListaViajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaViajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaViajes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblViajesProgramados)
                .addContainerGap())
        );

        btnEditarViaje.setText("Editar");
        btnEditarViaje.addActionListener(this::btnEditarViajeActionPerformed);

        btnEliminarViaje.setText("Eliminar");
        btnEliminarViaje.addActionListener(this::btnEliminarViajeActionPerformed);

        javax.swing.GroupLayout pnlEditarEliminarViajeLayout = new javax.swing.GroupLayout(pnlEditarEliminarViaje);
        pnlEditarEliminarViaje.setLayout(pnlEditarEliminarViajeLayout);
        pnlEditarEliminarViajeLayout.setHorizontalGroup(
            pnlEditarEliminarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarEliminarViajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditarEliminarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarViaje)
                    .addComponent(btnEliminarViaje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEditarEliminarViajeLayout.setVerticalGroup(
            pnlEditarEliminarViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarEliminarViajeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditarViaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarViaje)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        tblListaViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrlListaViajes.setViewportView(tblListaViajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlListaViajes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlTituloViajes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlProgramarViaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(scrlListaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlEditarEliminarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 5, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlProgramarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlListaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEditarEliminarViaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrlListaViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCapacidadMaxPrimeraViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadMaxPrimeraViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadMaxPrimeraViajeActionPerformed

    private void txtCapacidadMaxGeneralViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadMaxGeneralViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadMaxGeneralViajeActionPerformed

    private void cmbEstatusViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstatusViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstatusViajeActionPerformed

    private void cmbDestinoViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDestinoViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDestinoViajeActionPerformed

    private void cmbOrigenViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigenViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrigenViajeActionPerformed

    /**
     * Carga automáticamente las capacidades y disponibilidades iniciales al
     * seleccionar un tren.
     *
     * En modo edición: - La capacidad se actualiza según el tren seleccionado.
     * - La disponibilidad no se sobrescribe automáticamente, ya que podría
     * corresponder a un viaje con boletos ya vendidos.
     */
    private void cmbTrenViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTrenViajeActionPerformed
        TrenDTO trenSeleccionado = obtenerTrenSeleccionado();

        if (trenSeleccionado == null) {
            txtCapacidadMaxGeneralViaje.setText("");
            txtCapacidadMaxPrimeraViaje.setText("");
            txtDisponibilidadGeneralViaje.setText("");
            txtDisponibilidadPrimeraViaje.setText("");
            return;
        }

        txtCapacidadMaxGeneralViaje.setText(
                String.valueOf(trenSeleccionado.getCapacidadGeneral())
        );

        txtCapacidadMaxPrimeraViaje.setText(
                String.valueOf(trenSeleccionado.getCapacidadPrimeraClase())
        );

        /*
         * Al programar un viaje nuevo, la disponibilidad inicial debe ser igual
         * a la capacidad máxima del tren seleccionado.
         */
        if (!modoEdicion) {
            txtDisponibilidadGeneralViaje.setText(
                    String.valueOf(trenSeleccionado.getCapacidadGeneral())
            );

            txtDisponibilidadPrimeraViaje.setText(
                    String.valueOf(trenSeleccionado.getCapacidadPrimeraClase())
            );
        }
    }//GEN-LAST:event_cmbTrenViajeActionPerformed

    private void txtDisponibilidadGeneralViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisponibilidadGeneralViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisponibilidadGeneralViajeActionPerformed

    private void txtDisponibilidadPrimeraViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisponibilidadPrimeraViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisponibilidadPrimeraViajeActionPerformed

    /**
     * Registra un nuevo viaje o actualiza uno existente.
     */
    private void btnProgramarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgramarViajeActionPerformed
        if (!validarFormulario()) {
            return;
        }

        try {
            IViajeServicio viajeServicio = new ViajeServicio();

            TrenDTO trenSeleccionado = obtenerTrenSeleccionado();
            LocacionDTO origenSeleccionado = obtenerOrigenSeleccionado();
            LocacionDTO destinoSeleccionado = obtenerDestinoSeleccionado();

            ViajeDTO viajeDTO = new ViajeDTO();

            viajeDTO.setTrenId(trenSeleccionado.getId());
            viajeDTO.setOrigenId(origenSeleccionado.getId());
            viajeDTO.setDestinoId(destinoSeleccionado.getId());

            viajeDTO.setFechaHoraSalida(
                    construirFechaHoraIso(
                            dchFechaSalidaViaje.getDate(),
                            (Date) spnHoraSalidaViaje.getValue()
                    )
            );

            viajeDTO.setFechaHoraLlegadaEstimada(
                    construirFechaHoraIso(
                            dchFechaLlegadaViaje.getDate(),
                            (Date) spnHoraLlegadaViaje.getValue()
                    )
            );

            viajeDTO.setEstatus(cmbEstatusViaje.getSelectedItem().toString());

            viajeDTO.setCapacidadMaximaGeneral(
                    Integer.parseInt(txtCapacidadMaxGeneralViaje.getText().trim())
            );

            viajeDTO.setCapacidadMaximaPrimeraClase(
                    Integer.parseInt(txtCapacidadMaxPrimeraViaje.getText().trim())
            );

            viajeDTO.setDisponibilidadGeneral(
                    Integer.parseInt(txtDisponibilidadGeneralViaje.getText().trim())
            );

            viajeDTO.setDisponibilidadPrimeraClase(
                    Integer.parseInt(txtDisponibilidadPrimeraViaje.getText().trim())
            );

            if (!modoEdicion) {
                viajeServicio.registrar(viajeDTO);

                JOptionPane.showMessageDialog(
                        this,
                        "Viaje programado correctamente.",
                        "Registro exitoso",
                        JOptionPane.INFORMATION_MESSAGE
                );

            } else {
                viajeDTO.setId(idViajeSeleccionado);
                viajeServicio.actualizar(viajeDTO);

                JOptionPane.showMessageDialog(
                        this,
                        "Viaje actualizado correctamente.",
                        "Actualización exitosa",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }

            cargarViajes();
            limpiarFormulario();

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnProgramarViajeActionPerformed

    /**
     * Limpia el formulario al presionar el botón Limpiar.
     */
    private void btnLimpiarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarViajeActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnLimpiarViajeActionPerformed

    /**
     * Carga un viaje seleccionado de la tabla al formulario para editarlo.
     */
    private void btnEditarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarViajeActionPerformed
        int fila = tblListaViajes.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un viaje de la tabla.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            IViajeServicio viajeServicio = new ViajeServicio();

            String id = tblListaViajes.getValueAt(fila, 0).toString();
            ViajeDTO viaje = viajeServicio.buscarPorId(id);

            if (viaje == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "No fue posible encontrar el viaje seleccionado.",
                        "Viaje no encontrado",
                        JOptionPane.WARNING_MESSAGE
                );

                cargarViajes();
                return;
            }

            idViajeSeleccionado = viaje.getId();
            modoEdicion = true;

            seleccionarTrenEnCombo(viaje.getTrenId());
            seleccionarLocacionOrigenEnCombo(viaje.getOrigenId());
            seleccionarLocacionDestinoEnCombo(viaje.getDestinoId());
            cmbEstatusViaje.setSelectedItem(viaje.getEstatus());

            cargarFechaHoraEnComponentes(
                    viaje.getFechaHoraSalida(),
                    dchFechaSalidaViaje,
                    spnHoraSalidaViaje
            );

            cargarFechaHoraEnComponentes(
                    viaje.getFechaHoraLlegadaEstimada(),
                    dchFechaLlegadaViaje,
                    spnHoraLlegadaViaje
            );

            txtCapacidadMaxGeneralViaje.setText(
                    String.valueOf(viaje.getCapacidadMaximaGeneral())
            );

            txtCapacidadMaxPrimeraViaje.setText(
                    String.valueOf(viaje.getCapacidadMaximaPrimeraClase())
            );

            txtDisponibilidadGeneralViaje.setText(
                    String.valueOf(viaje.getDisponibilidadGeneral())
            );

            txtDisponibilidadPrimeraViaje.setText(
                    String.valueOf(viaje.getDisponibilidadPrimeraClase())
            );

            btnProgramarViaje.setText("Actualizar viaje");
            lblProgramarNuevoViaje.setText("Editar viaje");

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEditarViajeActionPerformed

    /**
     * Elimina un viaje seleccionado de la tabla.
     */
    private void btnEliminarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarViajeActionPerformed
        int fila = tblListaViajes.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione un viaje de la tabla.",
                    "Sin selección",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
                this,
                "¿Desea eliminar el viaje seleccionado?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            IViajeServicio viajeServicio = new ViajeServicio();

            String id = tblListaViajes.getValueAt(fila, 0).toString();
            viajeServicio.eliminar(id);

            JOptionPane.showMessageDialog(
                    this,
                    "Viaje eliminado correctamente.",
                    "Eliminación exitosa",
                    JOptionPane.INFORMATION_MESSAGE
            );

            cargarViajes();
            limpiarFormulario();

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEliminarViajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarViaje;
    private javax.swing.JButton btnEliminarViaje;
    private javax.swing.JButton btnLimpiarViaje;
    private javax.swing.JButton btnProgramarViaje;
    private javax.swing.JComboBox<String> cmbDestinoViaje;
    private javax.swing.JComboBox<String> cmbEstatusViaje;
    private javax.swing.JComboBox<String> cmbOrigenViaje;
    private javax.swing.JComboBox<String> cmbTrenViaje;
    private com.toedter.calendar.JDateChooser dchFechaLlegadaViaje;
    private com.toedter.calendar.JDateChooser dchFechaSalidaViaje;
    private javax.swing.JLabel lblCapacidadMaxGeneral;
    private javax.swing.JLabel lblCapacidadMaxPrimera;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblDisponibilidadGeneral;
    private javax.swing.JLabel lblDisponibilidadPrimera;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFechaEstimadaLlegada;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JLabel lblHoraEstimadaLlegada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblListaViajes;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblProgramarNuevoViaje;
    private javax.swing.JLabel lblSubtituloViajes;
    private javax.swing.JLabel lblTituloViajes;
    private javax.swing.JLabel lblTren;
    private javax.swing.JLabel lblViajesProgramados;
    private javax.swing.JPanel pnlEditarEliminarViaje;
    private javax.swing.JPanel pnlListaViajes;
    private javax.swing.JPanel pnlProgramarViaje;
    private javax.swing.JPanel pnlTituloViajes;
    private javax.swing.JScrollPane scrlListaViajes;
    private javax.swing.JSpinner spnHoraLlegadaViaje;
    private javax.swing.JSpinner spnHoraSalidaViaje;
    private javax.swing.JTable tblListaViajes;
    private javax.swing.JTextField txtCapacidadMaxGeneralViaje;
    private javax.swing.JTextField txtCapacidadMaxPrimeraViaje;
    private javax.swing.JTextField txtDisponibilidadGeneralViaje;
    private javax.swing.JTextField txtDisponibilidadPrimeraViaje;
    // End of variables declaration//GEN-END:variables

    /**
     * Configura el formato visual de los componentes de fecha y hora.
     */
    private void configurarComponentesFechaHora() {
        dchFechaSalidaViaje.setDateFormatString("dd-MM-yyyy");
        dchFechaLlegadaViaje.setDateFormatString("dd-MM-yyyy");

        Date fechaActual = obtenerFechaActualSinHora();

        // No permitir seleccionar días anteriores a hoy.
        dchFechaSalidaViaje.setMinSelectableDate(fechaActual);
        dchFechaLlegadaViaje.setMinSelectableDate(fechaActual);

        /*
     * Cuando cambia la fecha de salida, se ajusta la fecha mínima permitida
     * para la llegada.
         */
        dchFechaSalidaViaje.addPropertyChangeListener(
                "date",
                evt -> actualizarFechaMinimaLlegada()
        );

        configurarSpinnerHora(spnHoraSalidaViaje);
        configurarSpinnerHora(spnHoraLlegadaViaje);
    }

    /**
     * Configura un JSpinner para trabajar como selector de hora en formato
     * HH:mm.
     *
     * @param spinner Spinner a configurar.
     */
    private void configurarSpinnerHora(JSpinner spinner) {
        SpinnerDateModel modeloHora = new SpinnerDateModel();
        spinner.setModel(modeloHora);
        spinner.setEditor(new JSpinner.DateEditor(spinner, "HH:mm"));

        reiniciarSpinnerHora(spinner);
    }

    /**
     * Reinicia un spinner de hora a 00:00.
     *
     * @param spinner Spinner a reiniciar.
     */
    private void reiniciarSpinnerHora(JSpinner spinner) {
        Calendar calendario = Calendar.getInstance();
        calendario.set(Calendar.HOUR_OF_DAY, 0);
        calendario.set(Calendar.MINUTE, 0);
        calendario.set(Calendar.SECOND, 0);
        calendario.set(Calendar.MILLISECOND, 0);

        spinner.setValue(calendario.getTime());
    }

    /**
     * Configura las columnas de la tabla de viajes.
     *
     * La columna ID se mantiene oculta para utilizarla en edición y
     * eliminación.
     */
    private void configurarTablaViajes() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{
                    "ID",
                    "TREN",
                    "ORIGEN",
                    "DESTINO",
                    "FECHA SALIDA",
                    "ESTATUS",
                    "DISP. GENERAL",
                    "DISP. PRIMERA"
                },
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblListaViajes.setModel(modelo);

        tblListaViajes.getColumnModel().getColumn(0).setMinWidth(0);
        tblListaViajes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblListaViajes.getColumnModel().getColumn(0).setWidth(0);

        tblListaViajes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        tblListaViajes.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblListaViajes.getColumnModel().getColumn(2).setPreferredWidth(120);
        tblListaViajes.getColumnModel().getColumn(3).setPreferredWidth(120);
        tblListaViajes.getColumnModel().getColumn(4).setPreferredWidth(170);
        tblListaViajes.getColumnModel().getColumn(5).setPreferredWidth(110);
        tblListaViajes.getColumnModel().getColumn(6).setPreferredWidth(110);
        tblListaViajes.getColumnModel().getColumn(7).setPreferredWidth(110);
    }

    /**
     * Carga los viajes registrados en la tabla.
     */
    private void cargarViajes() {
        try {
            IViajeServicio viajeServicio = new ViajeServicio();
            List<ViajeDTO> viajes = viajeServicio.consultarTodos();

            DefaultTableModel modelo
                    = (DefaultTableModel) tblListaViajes.getModel();

            modelo.setRowCount(0);

            for (ViajeDTO viaje : viajes) {
                modelo.addRow(new Object[]{
                    viaje.getId(),
                    viaje.getTrenNombre(),
                    viaje.getOrigenNombre(),
                    viaje.getDestinoNombre(),
                    formatearFechaHoraParaTabla(viaje.getFechaHoraSalida()),
                    viaje.getEstatus(),
                    viaje.getDisponibilidadGeneral(),
                    viaje.getDisponibilidadPrimeraClase()
                });
            }

            lblViajesProgramados.setText(
                    viajes.size() + " viajes registrados"
            );

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar los viajes.\n"
                    + e.getMessage(),
                    "Error al cargar viajes",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Carga los estatus disponibles para los viajes.
     */
    private void cargarEstatusViajes() {
        cmbEstatusViaje.removeAllItems();

        for (EstatusViaje estatus : EstatusViaje.values()) {
            cmbEstatusViaje.addItem(estatus.name());
        }

        cmbEstatusViaje.setSelectedIndex(0);
    }

    /**
     * Carga en el combo los trenes activos disponibles para programar viajes.
     */
    private void cargarTrenesDisponibles() {
        try {
            ITrenServicio trenServicio = new TrenServicio();
            List<TrenDTO> trenes = trenServicio.consultarTodos();

            DefaultComboBoxModel<String> modeloCombo
                    = new DefaultComboBoxModel<>();

            modeloCombo.addElement("Seleccionar");
            trenesDisponibles.clear();

            for (TrenDTO tren : trenes) {
                if ("ACTIVO".equalsIgnoreCase(tren.getEstatus())) {
                    trenesDisponibles.add(tren);

                    modeloCombo.addElement(
                            tren.getCodigo() + " - " + tren.getNombre()
                    );
                }
            }

            cmbTrenViaje.setModel(modeloCombo);
            cmbTrenViaje.setSelectedIndex(0);

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar los trenes disponibles.\n"
                    + e.getMessage(),
                    "Error al cargar trenes",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Carga en los combos las locaciones activas disponibles para origen y
     * destino.
     */
    private void cargarLocacionesDisponibles() {
        try {
            ILocacionServicio locacionServicio = new LocacionServicio();
            List<LocacionDTO> locaciones = locacionServicio.consultarTodas();

            DefaultComboBoxModel<String> modeloOrigen
                    = new DefaultComboBoxModel<>();
            DefaultComboBoxModel<String> modeloDestino
                    = new DefaultComboBoxModel<>();

            modeloOrigen.addElement("Seleccionar");
            modeloDestino.addElement("Seleccionar");

            locacionesDisponibles.clear();

            for (LocacionDTO locacion : locaciones) {
                if (locacion.isActiva()) {
                    locacionesDisponibles.add(locacion);

                    String textoLocacion
                            = locacion.getClave() + " - " + locacion.getNombre();

                    modeloOrigen.addElement(textoLocacion);
                    modeloDestino.addElement(textoLocacion);
                }
            }

            cmbOrigenViaje.setModel(modeloOrigen);
            cmbDestinoViaje.setModel(modeloDestino);

            cmbOrigenViaje.setSelectedIndex(0);
            cmbDestinoViaje.setSelectedIndex(0);

        } catch (ServicioException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "No fue posible cargar las locaciones disponibles.\n"
                    + e.getMessage(),
                    "Error al cargar locaciones",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * Obtiene el tren seleccionado en el combo.
     *
     * @return Tren seleccionado o null si no se ha elegido uno.
     */
    private TrenDTO obtenerTrenSeleccionado() {
        int indice = cmbTrenViaje.getSelectedIndex();

        if (indice <= 0) {
            return null;
        }

        return trenesDisponibles.get(indice - 1);
    }

    /**
     * Obtiene la locación seleccionada como origen.
     *
     * @return Locación origen o null si no se ha elegido una.
     */
    private LocacionDTO obtenerOrigenSeleccionado() {
        int indice = cmbOrigenViaje.getSelectedIndex();

        if (indice <= 0) {
            return null;
        }

        return locacionesDisponibles.get(indice - 1);
    }

    /**
     * Obtiene la locación seleccionada como destino.
     *
     * @return Locación destino o null si no se ha elegido una.
     */
    private LocacionDTO obtenerDestinoSeleccionado() {
        int indice = cmbDestinoViaje.getSelectedIndex();

        if (indice <= 0) {
            return null;
        }

        return locacionesDisponibles.get(indice - 1);
    }

    /**
     * Construye una fecha y hora en formato ISO-8601 compatible con Instant.
     *
     * La captura se interpreta con la zona horaria local del sistema y se
     * convierte a UTC para almacenarse de forma consistente.
     *
     * @param fechaSeleccionada Fecha seleccionada en el JDateChooser.
     * @param horaSeleccionada Hora seleccionada en el JSpinner.
     * @return Fecha y hora en formato ISO-8601.
     */
    private String construirFechaHoraIso(Date fechaSeleccionada,
            Date horaSeleccionada) {

        LocalDate fechaLocal = fechaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        LocalTime horaLocal = horaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalTime()
                .withSecond(0)
                .withNano(0);

        LocalDateTime fechaHoraLocal = LocalDateTime.of(
                fechaLocal,
                horaLocal
        );

        return fechaHoraLocal
                .atZone(ZoneId.systemDefault())
                .toInstant()
                .toString();
    }

    /**
     * Valida únicamente la captura básica necesaria en la interfaz.
     *
     * Las reglas de negocio del viaje se validan en la capa de servicios.
     *
     * @return true si la captura básica del formulario está completa.
     */
    private boolean validarFormulario() {
        if (obtenerTrenSeleccionado() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar un tren.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            cmbTrenViaje.requestFocus();
            return false;
        }

        if (obtenerOrigenSeleccionado() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar una locación de origen.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            cmbOrigenViaje.requestFocus();
            return false;
        }

        if (obtenerDestinoSeleccionado() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar una locación de destino.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            cmbDestinoViaje.requestFocus();
            return false;
        }

        if (dchFechaSalidaViaje.getDate() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar la fecha de salida.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            dchFechaSalidaViaje.requestFocus();
            return false;
        }

        if (dchFechaLlegadaViaje.getDate() == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Debe seleccionar la fecha estimada de llegada.",
                    "Validación",
                    JOptionPane.WARNING_MESSAGE
            );
            dchFechaLlegadaViaje.requestFocus();
            return false;
        }

        return true;
    }

    /**
     * Limpia el formulario de viajes y restablece el modo de registro.
     */
    private void limpiarFormulario() {
        cmbTrenViaje.setSelectedIndex(0);
        cmbOrigenViaje.setSelectedIndex(0);
        cmbDestinoViaje.setSelectedIndex(0);
        cmbEstatusViaje.setSelectedIndex(0);

        dchFechaSalidaViaje.setDate(null);
        dchFechaLlegadaViaje.setDate(null);

        reiniciarSpinnerHora(spnHoraSalidaViaje);
        reiniciarSpinnerHora(spnHoraLlegadaViaje);

        txtCapacidadMaxGeneralViaje.setText("");
        txtCapacidadMaxPrimeraViaje.setText("");
        txtDisponibilidadGeneralViaje.setText("");
        txtDisponibilidadPrimeraViaje.setText("");

        idViajeSeleccionado = null;
        modoEdicion = false;

        btnProgramarViaje.setText("+ Programar viaje");
        lblProgramarNuevoViaje.setText("Programar nuevo viaje");
    }

    /**
     * Selecciona en el combo el tren cuyo id coincide con el indicado.
     *
     * @param trenId Identificador del tren.
     */
    private void seleccionarTrenEnCombo(String trenId) {
        for (int i = 0; i < trenesDisponibles.size(); i++) {
            TrenDTO tren = trenesDisponibles.get(i);

            if (tren.getId().equals(trenId)) {
                cmbTrenViaje.setSelectedIndex(i + 1);
                return;
            }
        }

        cmbTrenViaje.setSelectedIndex(0);
    }

    /**
     * Selecciona en el combo de origen la locación cuyo id coincide con el
     * indicado.
     *
     * @param locacionId Identificador de la locación de origen.
     */
    private void seleccionarLocacionOrigenEnCombo(String locacionId) {
        for (int i = 0; i < locacionesDisponibles.size(); i++) {
            LocacionDTO locacion = locacionesDisponibles.get(i);

            if (locacion.getId().equals(locacionId)) {
                cmbOrigenViaje.setSelectedIndex(i + 1);
                return;
            }
        }

        cmbOrigenViaje.setSelectedIndex(0);
    }

    /**
     * Selecciona en el combo de destino la locación cuyo id coincide con el
     * indicado.
     *
     * @param locacionId Identificador de la locación de destino.
     */
    private void seleccionarLocacionDestinoEnCombo(String locacionId) {
        for (int i = 0; i < locacionesDisponibles.size(); i++) {
            LocacionDTO locacion = locacionesDisponibles.get(i);

            if (locacion.getId().equals(locacionId)) {
                cmbDestinoViaje.setSelectedIndex(i + 1);
                return;
            }
        }

        cmbDestinoViaje.setSelectedIndex(0);
    }

    /**
     * Carga una fecha ISO-8601 en los componentes gráficos de fecha y hora.
     *
     * @param fechaHoraIso Fecha y hora almacenada en formato ISO-8601.
     * @param dateChooser Componente de fecha.
     * @param spinnerHora Componente de hora.
     */
    private void cargarFechaHoraEnComponentes(String fechaHoraIso,
            JDateChooser dateChooser,
            JSpinner spinnerHora) {

        if (fechaHoraIso == null || fechaHoraIso.isBlank()) {
            dateChooser.setDate(null);
            reiniciarSpinnerHora(spinnerHora);
            return;
        }

        try {
            Instant instant = Instant.parse(fechaHoraIso);
            ZonedDateTime fechaHoraLocal = instant.atZone(ZoneId.systemDefault());

            Date fechaParaDateChooser = Date.from(
                    fechaHoraLocal.toLocalDate()
                            .atStartOfDay(ZoneId.systemDefault())
                            .toInstant()
            );

            dateChooser.setDate(fechaParaDateChooser);
            spinnerHora.setValue(Date.from(fechaHoraLocal.toInstant()));

        } catch (DateTimeParseException e) {
            dateChooser.setDate(null);
            reiniciarSpinnerHora(spinnerHora);
        }
    }

    /**
     * Obtiene la fecha actual con la hora establecida en 00:00:00.
     *
     * @return Fecha actual sin información de hora.
     */
    private Date obtenerFechaActualSinHora() {
        return obtenerFechaSinHora(new Date());
    }

    /**
     * Elimina la información de hora de una fecha.
     *
     * @param fecha Fecha a normalizar.
     * @return Fecha con hora 00:00:00.
     */
    private Date obtenerFechaSinHora(Date fecha) {
        Calendar calendario = Calendar.getInstance();
        calendario.setTime(fecha);
        calendario.set(Calendar.HOUR_OF_DAY, 0);
        calendario.set(Calendar.MINUTE, 0);
        calendario.set(Calendar.SECOND, 0);
        calendario.set(Calendar.MILLISECOND, 0);

        return calendario.getTime();
    }

    /**
     * Ajusta la fecha mínima seleccionable para la llegada.
     *
     * Si existe fecha de salida, la llegada no puede ser anterior a esa fecha.
     * Si no existe fecha de salida, la llegada no puede ser anterior al día
     * actual.
     */
    private void actualizarFechaMinimaLlegada() {
        Date fechaSalida = dchFechaSalidaViaje.getDate();

        Date fechaMinimaLlegada;

        if (fechaSalida != null) {
            fechaMinimaLlegada = obtenerFechaSinHora(fechaSalida);
        } else {
            fechaMinimaLlegada = obtenerFechaActualSinHora();
        }

        dchFechaLlegadaViaje.setMinSelectableDate(fechaMinimaLlegada);

        Date fechaLlegadaSeleccionada = dchFechaLlegadaViaje.getDate();

        /*
     * Si ya había una fecha de llegada elegida y ahora queda fuera del rango
     * permitido, se limpia para obligar a seleccionar una fecha válida.
         */
        if (fechaLlegadaSeleccionada != null
                && obtenerFechaSinHora(fechaLlegadaSeleccionada)
                        .before(fechaMinimaLlegada)) {

            dchFechaLlegadaViaje.setDate(null);
        }
    }

    /**
     * Convierte una fecha ISO-8601 almacenada en UTC a formato local para
     * mostrarla de forma amigable en la interfaz.
     *
     * @param fechaHoraIso Fecha y hora en formato ISO-8601.
     * @return Fecha formateada como dd-MM-yyyy HH:mm.
     */
    private String formatearFechaHoraParaTabla(String fechaHoraIso) {
        if (fechaHoraIso == null || fechaHoraIso.isBlank()) {
            return "";
        }

        try {
            Instant instant = Instant.parse(fechaHoraIso);

            ZonedDateTime fechaHoraLocal = instant.atZone(
                    ZoneId.systemDefault()
            );

            DateTimeFormatter formatoTabla
                    = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

            return fechaHoraLocal.format(formatoTabla);

        } catch (DateTimeParseException e) {
            return fechaHoraIso;
        }
    }

}
